src/clincoded/static/components/app.js, src/clincoded/static/scss/clincoded/_base.scss, src/clincoded/static/scss/clincoded/modules/_navbar.scss
This is a temporary UI to enable Persona login/logout. It appears in a little window-relative tab in the upper right of the header area.
As part of #29, I’m refactoring the navigation components to be more general, and I’ll implement the navigation you see in the upper right of the Tam/Selina UI document as a proposed final UI, including Persona login.
Sorry about the temporary PR confusion. I realized I used the ENCODED branch naming “standard” (which doesn’t actually exist) instead of the ClinGen one (which does), so I renamed it which closed the previous PR.
=> Connects to #30 Enable Persona login system

package.json, src/clincoded/static/components/create_gene_disease.js, src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/rest.js, src/clincoded/static/libs/bootstrap/form.js, src/clincoded/static/libs/parse-pubmed.js
Removed PubMed XML-parsing code and instead using one adapted from [an external GitHub project](https://github.com/standard-analytics/pubmed-schema-org/blob/master/lib/pubmed.js). This hopefully will make us more reliably parse PubMed XML when adding articles to the GDM.
Updated the Curation Central Gene header links to be clearer to Curators.
Loading html5shiv library from GitHub instead of npm because it was removed from the npm directory.
=> Connects to #56 ft curation central

src/clincoded/static/components/curation_central.js
If 'gdm' and 'pmid' are defined in the curation-central url (/curation-central/?gdm={gdm_id}&pmid={pmid}) the specified pmid will be automatically selected on page load.
Example: http://localhost:6543/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=7913883
=> Connects to #111. Allow for pmid specification via url in curation central

src/clincoded/static/components/dashboard.js
Update displays model text for models without (HP:######) properly (Other, Codominant, Autosomal unknown):
=> Connects to #123. Dashboard - model text not displaying properly in all cases

src/clincoded/tests/data/inserts/annotation.json, src/clincoded/tests/data/inserts/assessment.json, src/clincoded/tests/data/inserts/functional.json, src/clincoded/tests/data/inserts/gdm.json, src/clincoded/tests/data/inserts/segregation.json, src/clincoded/tests/data/inserts/statistic.json
* Fixes momentjs warning mentioned by @kilodalton in #129.
* Existing test data sorts by date properly now (@tsneddon's records being displayed):
* Corrected ownership of some of @tsneddon's test data ('tsneddon@stanford' -> 'tsneddon@stanford.edu')
=> Connects to #134. Convert dateTime fields in test data to ISO format

src/clincoded/static/libs/parse-pubmed.js
CollectiveName XML tag now maps to our author field so that we don’t have empty author properties when receiving this kind of PubMed XML.
Before this change, PubMed ID 12345678 would give us an empty author property in our article object because their author information was in the CollectiveName tag, and we only processed the LastName and FirstName tags. With this change, we get a full author property with PubMed ID 12345678.
=> Connects to #128 Handle CollectiveName author tag in PubMed XML

src/clincoded/static/components/app.js, src/clincoded/static/components/errors.js, src/clincoded/static/components/home.js
* Updated text on homepage (visible on / regardless of login status):
* Pressing the ClinGen icon on upper left takes you to homepage
* Updated text on access denied/not available page (primarily for attempting to access the Dashboard while logged out):
* Updated error messages + homepage text to be encapsulated in 'container' div element so the text aligns with left edge of logo image, instead of left edge of browser window (ex: 404 page):
=> Connects to #137. Updated Logged out page and warning messages

src/clincoded/static/components/app.js
* Hides menu items other than 'Login' when logged out
* Hides 'Account' menu item across the board as the page does not exist at the moment
Logged out:
Logged in:
=> Connects to #145. Hide menu items when logged out

src/clincoded/static/components/create_gene_disease.js, src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/scss/clincoded/_variables.scss, src/clincoded/static/scss/clincoded/modules/_curator.scss
* Added Record Header to group curation, displaying the current gene and disease details, and the curator history, just as you see at the top of the content of the Curation Central page.
* Made the OMIM ID adding/editing functional on all pages it will appear on, including the existing Group Curation page.
* Displaying the current article summary below the record header.
=> Connects to #135 ft record header

src/clincoded/search.py, src/clincoded/static/components/dashboard.js
Previous natural sorting of search results on dashboard (localhost:6543/dashboard):
New natural sorting of search results (note the dates):
This fix also frees up the dashboard page from having to sort the data on every load.
=> Connects to #158. Reenable elasticsearch dateTime sort

src/clincoded/static/components/create_gene_disease.js
Removed the ```status``` property from the code that POSTs a gdm object. Confirmed this successfully creates a gdm on submit without a 422 error.
=> Connects to #162 Remove "status" from GDM-creation JS code

src/clincoded/static/components/app.js
Pressing on the 'X' gets rid of the notice until a page is refreshed.
Also added Notice class to app.js for the ability to create similar notices as needed:
=> Connects to #138. Create demo indicator for demo release

src/clincoded/static/components/app.js, src/clincoded/static/components/home.js
* Header ClinGen logo URL changes between '/' or '/dashboard/' depending on login status
* Navigating to the Homepage ('/') after login forwards you to /dashboard/ (kinda buggy still). Triggers on logging in, and manually navigating to /.
* Bugs/caveats: forwarding from / to /dashboard/ happens after rendering the page, so there is a delay; on Firefox, a 'Network request failed' error is displayed before the forwarding to dashboard kicks in.
=> Connects to #169. Change Homepage behavior

src/clincoded/static/components/app.js, src/clincoded/static/components/curation_central.js, src/clincoded/static/components/globals.js
GET requests to external sites now use the protocol (http/https) of the current site. Also bring back a lot of app.js code from ENCODE; had ripped out a lot when I had a dummy mechanism for loading curation pages. My mods aren’t needed anymore, and we can use something more ENCODE-like.
=> Connects to #174 ft http

src/clincoded/static/components/group_curation.js, src/clincoded/static/libs/bootstrap/form.js
* When a new Group Curation page comes up, the Method 2 genotyping method dropdown should be disabled. Making a selection from Method 1 should then enable the Method 2 dropdown.
* When an existing Group Curation page is edited and no entry was made in the Method panel at all before, then both the Method 1 and Method 2 dropdowns should show “Select,” and the Method 2 dropdown should be disabled.
* When an existing Group Curation page is edited and an entry aside from the Method 1 and Method 2 dropdowns was made in the Method section, then both the Method 1 and Method 2 dropdowns should show “Select,” and the Method 2 dropdown should be disabled.
* When an existing Group Curation page is edited and an entry had been selected in Method 1, the Method 2 dropdown should come up enabled, with …
=> Connects to #181 ft genotyping bug

src/clincoded/schemas/group.json, src/clincoded/static/components/group_curation.js
Note checkmark next to "None" dropdown option + "Unknown" item in ethnicity:
Also works for Genotyping methods (if both Genotyping methods are selected and the first is set to None, the second is automatically shifted to the first position):
=> Connects to #183 and #180. Allow users to select "None" on dropdowns + add "Unknown" to ethnicity dropdowns

src/clincoded/root.py
The portal_title property now properly references 'ClinGen' in the homepage.
=> Connects to #189. Remove ENCODE refs

src/clincoded/static/components/curation_central.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
When literature list is empty in curation central the instruction text displays:
When literature list is not empty, the text is not displayed:
=> Connects to #140. Add instruction text when empty PMID list in curation-central

src/clincoded/static/components/curation_central.js
One place was still using the old method (owner property) to decide whether to display the message, “Currently, only the curator who adds a paper…” above the abstract. This caused this message to always display even when the current user has selected a paper they added.
This fixes that to use the newer method to detect and compare users.
=> Connects to #214 Fix Curation Central note bug

src/clincoded/static/components/family_curation.js, src/clincoded/types/__init__.py
To test this change (screen shot of difference at https://github.com/ClinGen/clincoded/issues/7):
1. From Curation Central, create a new group and fill in all required fields. Note what diseases you’re entering because that becomes relevant on the family curation page later.
1. Back at Curation Central, click **Add family information**.
1. The new line in the “Family – Common Disease & Phenotypes” panel appears, titled **Orphanet Disease Associated with Group** and displaying the diseases you entered for the group in the first step.
1. Go back to Curation Central (either by creating the family, or just clicking the back button).
1. Click **Family +** to create an unassociated family.
1. The **Orphanet Disease Associated with Group** is missing, as we have no associated group to contribute …
=> Connects to #7 ft group header

src/clincoded/static/components/curator.js, src/clincoded/static/components/family_curation.js
Just text changes to correct/improve wording:
* Curator palette nows shows “Add new Family to this Group” instead of “Add family information.”
* Family curation page now shows “# parents who are unaffected carriers” instead of “Are parents unaffected carriers?” for both creating/editing and viewing.
* Also, it now shows “# affected with 2 different variants or homozygous for 1” instead of “# affected with 2 variants or homozygous for 1.”
=> Connected to #7 Wording changes

src/clincoded/static/components/dashboard.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
As brought up and discussed in #95 and #254:
=> Connects to #254. Gray out 'View all GDM' link on Dashboard

src/clincoded/search.py
Recent History items should now sort properly on dashboard.
=> Connects to #251. Fix search sorting to use new date_created field

src/clincoded/static/components/curator.js
GDMs, groups, and families were all carrying over the date_created value between writes to the DB, but annotations were not. This adds annotations to the objects that do that.
1. Create a GDM.
2. Add a PMID; any will do, but note what PMID you use for the next step.
3. Open a window with ```/evidence``` and look through the list until you find one matching your PMID. Open that in its own window to see its JSON, and just keep it open.
4. Record the date_created and last_modified of the annotation.
4. Back on your ClinGen window, add a family.
5. Go back to the /evidence object for your PMID and refresh it.
6. Compare date_created and last_modified with what you had recorded before. The date_created doesn’t change, and last_modified does.
7. If you like, do the same with adding a group.
=> Connects to #246 Add date_created to annotation properties

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/dashboard.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
No visible change, but a user should not be able to re-add an article if it has been already associated with a GDM, regardless of ownership (this might change in the future).
Testing:
1. Create GDM
2. Add a PMID to GDM.
3. Check the GDM's JSON object. The size of `annotations` should be 1.
4. Add a new/different PMID to GDM. The size of `annotations` should be 2.
5. Add the first PMID again. The interface should select that particular PMID, but the size of the JSON's `annotations` should remain 2.
=> Connects to #249. Fix creation of multiple evidences w/ same article for same GDM

.travis.yml
--Reduce sleep time between checks when Sauce Labs sauce connect tunnel is open
--Reduce timeout time so that tests don't hang when stuck (occupying a sauce tunnel connection)
--Don't start test unless the "tunnel ready" file actually has a process number
--Wait until Sauce Connect process is fully closed (which sends signal to Sauce Connect to close the tunnel connection [because we are limited to 5 concurrent tunnels to Sauce Labs for free accounts and if the tunnels are not closed it blocks further tests ]) rather than looping to ensure a kill of Sauce Connect process.
=> Connects to #142 kd sauce connect check pid

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js
In this implementation for the PMID and OMIM ID add/change modals the "Cancel" button (or first button after input field  [if the "Submit" button were before the Cancel button that would be the default instead]) becomes the new target after a user has clicked in the input field (even if the input field is still highlighted as "active"). Subsequently hitting "enter" (which is then being interpreted as a "mouse click" event on the cancel button) then triggers the modal to close without submitting any info present in the input field  or warning that the info entered is being discarded (the "Cancel" button is linked to the "cancelForm" method which only closes the modal).
Using the event.detail property in cancelForm we can determine if the user has actually clicked the cancel button (not …
=> Connects to #144 prevent enter/return from closing add PMID/OMIM ID modals

src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js
1. From Record Curation, click either **Group +** or **Family +**.
2. Under the Common Diseases and Phenotypes panel, the second item that used link to PhenExplorer now links to HPO Browser, and the link text and tooltip reflect this change.
3. The link is now http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000118.
3a. Unfortunately, today this links seems to have a lot of problems that vary depending on when you try it.
=> Connects to #268 Change to hpo browser link

src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js
1. From the Record Curation page, click **Family +**. You’ll go to the Family Curation page.
2. Scroll down to the “Family — Variants segregating with Proband” panel. All instructional text within that panel uses “VariationID” instead of the previous “VariantID,” as does the “ClinVar VariationID” field title.
1. Again from the Record Curation page, click **Individual +**. You’ll go to the Individual Curation page.
2. Scroll down to the “Family — Associated Variant(s) panel. All instructional text within that panel uses “VariationID” instead of the previous “VariantID,” as does the “ClinVar VariationID” field title.
3. Scroll back to the top panel and note that it says “Diseases & Phenotypes” instead of “Common Diseases & Phenotypes.”
3. Create an Individual for the next step, and go back …
=> Connects to #282 ft prealpha2

Gruntfile.js, README.rst, buildout-dev.cfg
For development it is more helpful to be able to look at unminified JS.
To test:
`bin/buildout -c buildout-dev.cfg`
This sets the new default for grunt to have an env of development (you can still run `bin/grunt --env=production` to have JS be minified, or alternatively run buildout without the dev config file `bin/buildout` as before which make `bin/grunt` no longer default to "development" unminified mode)
Results:
--on the filesystem:  `src/clincoded/static/build/bundle.js`   will no longer be minified  (code should be readable)
--on browser: 
-Launch site after running buildout as above
-Open "Chrome Dev Tools" in Chrome
-Navigate to "Sources" and look for bundle.js and click on it (static/build/bundle.js)
-bundle.js should be readable and maintain original formatting (i.e. it is …
=> Connects to #265 allow grunt unminified JS, update docs

src/clincoded/static/libs/bootstrap/form.js
To text fix, follow @mrmin123 procedure:
1. Navigate to site in Firefox browser (I’m using FF 37.0.2)
2. Create/navigate to GDM
3. Add/select evidence
4. Click button to add Group, Family, Individual, or Experimental Data item
5. Fill out form
6. Hit Submit
With this fix, you’ll now go to the appropriate submit results page.
=> Connects to #292 Don’t write to <option> in DOM

src/clincoded/static/inline.js
Google Analytics tag added for beta instances.
New tag shows correct tracking ID in Google Analytics debugger plugin for various instances
Beta URLS (use beta tracker: UA-49947422-6) info in console shown using Chrome Google Analytics debugger plugin:
All other non-production URLs (default to demo tracker: UA-49947422-5) info in console shown using Chrome Google Analytics debugger plugin:
Google Analytics shows beta tracker being used on test "beta" site (not the real beta site):
=> Connects to #327 kd googleanalytics beta tag

src/clincoded/static/components/app.js
The red 'Note: This is a demo version of the site. Any data you enter will not be permanently saved.' notice bar should disappear when on a production URL (curation.clinicalgenome.org). 
Domain matches production URL:
Domain does not match production URL:
Note: this was tested by changing the regex matching to localhost and testing locally, as we do not have the production site to test against.
=> Connects to #304. Conditional handling of demo notice bar

development.ini
Building on ticket #304/PR #353 (conditional display of demo notice), allow login from testing URL 
To test:
-`sudo nano /etc/hosts`
-add the line:
`127.0.0.1       curation.clinicalgenome.org`
-start app
-go to http://curation.clinicalgenome.org:6543
-comment out later or you won't be able to access the production site from your machine
User can login using either  http://localhost:6543 or http://curation.clinicalgenome.org:6543 and will be able to access app.
from http://localhost:6543  (see demo notice)
from http://curation.clinicalgenome.org:6543/  (do not see demo notice)
=> Connects to #355 allow dev persona login from clinicalgenome.org

src/clincoded/static/components/curation_central.js
Two changes:
1. Remove check for input PMID character length
2. Changed check for empty response from NCBI so that the Invalid PMID error doesn't flash as a valid entry is returned
Testing:
1. Create GDM
2. Add valid PMID and confirm that the error message does not flash before the modal disappears
3. Attempt to add invalid PMID and confirm that the error message still works as intended
=> Connects to #267. PMID lookup changes

src/clincoded/static/components/experimental_curation.js
Testing
1. Create GDM
2. Add PMID
3. Add Experimental Data item WITHOUT assessment
4. Edit/View the item and assess.
5. Confirm at `/assessment/` that the new assessment has the correct evidenceType ('Evidence' column) of the experimental data type, not the text 'experimental':
=> Connects to #362. Experimental Data Assessment evidenceType

src/clincoded/schemas/group.json, src/clincoded/static/components/group_curation.js
1. Create GDM
2. Add PMID
3. Create Group item with only the required fields (leave previously required 5 fields blank)
4. Confirm Group item is added successfully
5. Create Group item with a few of the previously required fields filled
6. Confirm Group item is added successfully
7. Create Group item with all of the previously required fields filled
8. Confirm Group item is added successfully
9. Confirm Group curation is less tedious
Fields are now not required:
New Group item created w/ previously required fields being blank:
New Group item created w/ some of the previously required fields being filled:
New Group item created w/ all of the previously required fields being filled:
=> Connects to #335. Make certain Group curation fields unrequired

src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/individual_submit.js
On both family_curation and experimental_curation, added GET for the object being curated on so the most updated version of the object is updated, and re-instantiated assessmentTracker after the fact. Also moved the first assessmentTracker instantiation out of render into componentWillReceiveProps so that it is not re-written with old data on re-render.
1. Create GDM
2. Add PMID
3. Create experimental data and/or family item w/o assessment
4. Go to the item's View page
5. Assess and Update
6. Without refreshing the page, re-assess and update.
7. Confirm at `/assessments/` that only one assessment item exists for the parent experimental data/family item and that it has the correct value.
8. Refresh the View page, re-assess and update.
9. Confirm at `/assessments/` that only one assessment …
=> Connects to #366. Connects to #367. Connects to #358. Connects to #320. Fix assessments from View page + others

src/clincoded/static/components/assessment.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_curation.js, src/clincoded/static/libs/bootstrap/form.js, src/clincoded/static/scss/clincoded/modules/_form.scss
The fix pursued for #372 was to disable the button on form submit.
For Assessments from the View pages, the button will be disabled while the REST calls are happening in the background:
For the Groups, Family, Individual, Experimental Data creation and edit forms, as well as the Variants assessment form, the button will be disabled and display an animated cog while the REST calls are happening in the background, before the user is forwarded to the next page on a successful submit: 
Testing:
1. Create GDM
2. Add PMID
3. Create Group/Family/Individual/Experimental Data item(s), and confirm that the cogs show up on Submit button and that the button is disabled before taking you to next page.
* Bonus step: Attempt to submit a form that is rejected (mainly via input of not-found Orphanet and …
=> Connects to #372. Disable submit buttons on click

src/clincoded/static/components/family_curation.js
The View Family assessment panel now only appears if something in the family’s segregation has been set. This lets it be more consistent with the Curate/Edit Family page’s assessment.
1. Create a GDM and add a PMID.
2. Click **Family +** to add a new unassociated family with any data, but with nothing set in the segregation panel — leave it empty.
3. Save the new family and return to Record Curation.
4. Click the **View** link for the new family. Verify no Segregation Assessment panel appears.
5. Close the View window and edit the family. Add anything to its segregation and save it.
6. View the family again. Verify the assessment panel appears and can be used.
=> Connects to #344 View Family assessment panel conditional display

src/clincoded/static/components/individual_curation.js
Testing:
1. Create GDM
2. Add PMID
3. Create family w/ proband
4. Edit proband individual, and confirm that the notice does not appear
5. Attempt to add another indiviudal to family, and confirm that the notice does not appear
6. Create family w/o proband
7. Attempt to add individual to new family, and confirm that the notice does appear
Notice correctly disappears when editing proband individual:
Still does not appear when adding/editing individual to family w/ proband:
Still appears when adding/editing individual to family w/ no proband:
=> Connects to #384. Proband notice

src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/family_submit.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js
Added Cancel button to Group, Family, Individual, and Experimental Data curation pages:
Testing:
1. Create GDM, add PMID to it.
2. Go to create a Group and confirm that Cancel button takes you back to curation central.
3. Create Group. Press Edit from the submit page, and confirm that the Cancel button takes you back to submit page.
4. From curation central, Edit the Group entry and confirm that the Cancel button takes you back to curation central.
5. Repeat steps 2-4 with Family, Individual, and Experimental Data forms
Family link changes to 'View/Assess' when it has segregation info (thus making it assessable):
Also made Experimental Data item links to 'View/Assess', since they're all assessable by default:
Testing:
1. Create GDM, add PMID to it
2. Create Family w/o segregation data, …
=> Connects to #275. Connects to #345. Connects to #307. Cancel button + View/Assess links + HPO Links

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/rest.js, src/clincoded/static/libs/parse-pubmed.js
Testing:
1. Create GDM and add PMID to it
2. Add Group/Family/Individual object w/ PMID not already in db
3. Confirm that the new PMID is associated with the object by View/Editing it
4. Confirm that the new PMID exists in the db by checking /articles/
5. Attempt to add/edit in an invalid PMID
6. Attempt to add/edit in multiple new PMIDs
7. Attempt to add/edit in mix of new PMIDs and PMIDs already in the db
Additional changes:
* Refined check for valid PMID entries in curation module
* Incorporate getRestDatasXml function
=> Connects to #334. Add any PMID in curation pages

src/clincoded/schemas/experimental.json, src/clincoded/static/components/experimental_curation.js
To test:
1. Start local instance
1. Create GDM-> Add PMID
1. Add Experimental->Experiment type = "Protein Interactions"
1. In the "Protein Interactions" section: review the selections in the dropdown for "Method by which interaction detected":
Items corrected and display in the new alphabetical order:
New items + order:
"affinity chromatography technology (MI:0004)",
"coimmunoprecipitation (MI:0019)",
"comigration in gel electrophoresis (MI:0807)",
"electron microscopy (MI:0040)",
"protein cross-linking with a bifunctional reagent (MI:0031)",
"pull down (MI:0096)",
"synthetic genetic analysis (MI:0441)",
"two hybrid (MI:0018)",
"x-ray crystallography (MI:0114)"
**Note**: Also included in PR: fixed eslint errors about semicolons in experimental_curation.js
**Note2**: As indicated on …
=> Connects to #419 kd add molecular interactions

src/clincoded/static/inline.js
curation-test instances will re-use the Google Analytics tracker originally created for curation-beta (curation-beta being defunct since November 2015, does not need it).
=> Connects to #491 configure curation-test tracker

src/clincoded/tests/test_upgrade_user.py, src/clincoded/upgrade/experimental.py, src/clincoded/upgrade/user.py
* Fixes upgrade scripts associated with item delete function (#453) and experimental data dropdown changes (#419)
Testing (applicable on AWS instances):
* Confirm that users with emails not included in users upgrade script (non-Stanford staff) have user group value of `['curator']` (need to use `#!edit-json` URL to see)
* If loading production data, confirm that previously-created Protein Interaction experimental data entries with old enum values pass validation and have the correct value under the `experimentalInteractionDetection` field
=> Connects to #497 Update upgrade scripts

src/clincoded/static/libs/bootstrap/form.js
1. Create new GDM and add PMID.
2. Create and save a group with basic information, then create an associated family and fill in its name.
3. Click the Copy Orphanet IDs from Associated Group button to put the group's Orphanet ID into the field.
4. Remove that value from that field.
5. Click Copy Orphanet IDs from Associated Group again. Verity if repopulates the field properly. Previously, the field would stay blank, and no console errors would display.
=> Connects to #500 Copy Orphanet ID from Group bug fix

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_curation.js
Testing:
1. Create GDM
2. Open GDM window in two separate tab/windows. Add a PMID in both w/o refreshing the pages, and confirm that both PMIDs are visible after the operations
3. Open two separate Add Group pages. Add a Group in both w/o refreshing the pages, and confirm that both Groups are visible after the operations
4. Open two separate Add Family pages. Add a Family in both w/o refreshing the pages, and confirm that both Families are visible after the operations
* Repeat above, but with adding the Families under the same Group
5. Open two separate Add Individual pages. Add an Individual in both w/o refreshing the pages, and confirm that both Individuals are visible after the operations
* Repeat above, but with adding the Individuals under the same Group
* Repeat above, but with …
=> Connects to #515. Get updated parent on edits

src/clincoded/static/components/individual_submit.js
* Fixes UI bug where the 'Add another individual' button in the Individual Submit page would have overflowing text at certain resolutions.
Testing:
1. Add GDM
2. Add PMID, then individual
3. Resize browser in resulting Individual Submit page to make sure that the text does not overflow
=> Connects to #515. UI bug found while testing

development.ini
General setup: 
----------------------------------------------------------------------------------------
**Testing Windows versions + Browsers via VirtualHost on a Mac:​**
—Install VirtualBox via their website or `brew install Caskroom/cask/virtualbox`
—Install Windows on it  https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/
—When OS is running, IE/Edge is already installed…use this browser to  find and install Chrome and Firefox
—You should be able to access any clinicalgenome production and demo URLs
**​To access ​_localhost_​ (code running on Mac) from VM on win7:​**
-- Start Start button , click All Programs, click Accessories, right-click Notepad, and then click Run as administrator. 
— Edit file `C:\Windows\System32\drivers\etc\hosts`
— Add to file 
`10.0.2.2    localhost` …
=> Connects to #552 allow login with alternative win-localhost

src/clincoded/static/components/experimental_submit.js, src/clincoded/static/components/family_submit.js, src/clincoded/static/components/group_submit.js, src/clincoded/static/components/individual_submit.js
This PR is for moving the citation info boxes to be above titles on evidence submission pages.
Testing for #333:
1. Create a new Gene-Disease record.
2. On the new GDM page, add a PMID to enable the display of the Evidence column on the far right.
3. Click on any of evidence options (e.g. "Family").
4. On the subsequent curation information page, fill out the required fields and save the submission form.
5. The expected result should be that the citation info box is displayed above the title (see screenshot below).
=> Connects to #333. Swap citation info box and title positions on submit pages.

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/provisional_curation.js
This PR is for fixed the issue in which clicking "Cancel" button in the modal box fails to dismiss modal box in IE11/Win7.
Testing for #442:
1. Go to any existing GDM.
2. Click on "Add New PMID(s)" button or the "Add" (or "Edit") link next to the OMIM ID label.
3. Click on "Cancel" button in modal box.
4. The expected result is that the modal box will be dismissed.
=> Connects to #442. Fixed modal box Cancel button in IE.

src/clincoded/static/components/assessment.js, src/clincoded/static/components/experimental_curation.js
Testing:
1. Create GDM and add PMID
2. Navigate to add an Experimental Data object
3. Set Type to 'Biochemical Function' and subtype to 'A'.
4. Fill out the form, including Assessment, but DO NOT SUBMIT. Instead, change the subtype to 'B' and confirm that the entire form resets, including Assessment.
5. Repeat steps 3 and 4, but with Type 'Expression' and subtype 'A'.
6. Repeat steps 3 and 4, but with any other Type, to any other Type (note the Assessment value)
=> Connects to #527. Form clears on Experimental Data curation type and subtype changes

src/clincoded/static/components/assessment.js
Previous changes to assessment module made it not work on Variant curation page (calling form functions before form is rendered)
Testing:
* Create GDM, add PMID, add item with Variant
* Check Variant's curation page and ensure that it works (display + assessment)
* Check other pages where assessment occurs (Experimental Data, Family, Individual)
=> Connects to #577. Fix issues with assessment

src/clincoded/static/components/curator.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js
This PR is to address the requested text changes or additions in #562, #568 and #569.
**Testing steps for #562:**
1. Go to a GDM page and add a new PMID.
2. From the far-right column, choose either Group, Family, or Individual curation.
3. On the subsequent curation page, the expected result will be that all "HP_" instances had been replaced with "HP:" instances.
**Testing steps for #568:**
1. Go to a GDM page and add a new PMID.
2. From the far-right column, choose either Group, Family, or Individual curation.
3. On the subsequent curation page, the expected result will be that all "Group Name", "Family Name" and "Individual Name" instances had been replaced with "Group Label", "Family Label" and "Individual Label" instances.
**Testing steps for #569:**
1. Go to a GDM page and add a new …
=> Connects to #562. Connects to #568. Connects to #569. Text changes.

src/clincoded/static/components/curation_central.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR is to address the need to differentiate the added/selected PMID on the GDM page requested in #409.
**Testing steps for #409:**
1. Go to any given GDM page and add a new PMID. Upon successfully adding the PMID and dismissing the modal box, the newly added PMID should be shown within the viewable area of the scrollable far-left column.
2. Refreshing the GDM page should show the selected PMID even after it was scrolled off the bounding viewable area.
3. From the Dashboard page, clicking on a given PMID from the "Your Recent History" list should show the selected PMID in the far-left column on the subsequent GDM page.
4. Lastly, the selected PMID is highlighted in thicker blue border to differentiate itself from the non-selected ones. To help the user to associate the selected PMID …
=> Connects to #409. Anchor added or selected PMID.

src/clincoded/static/components/curator.js, src/clincoded/static/components/variant_curation.js, src/clincoded/tests/data/inserts/variant.json
Following tickets #543 (Obtain preferred HGVS name) and #559 (Schema change), this one display ClinVar preferred  name in curation-central page and variant curation page.
**Changes**
- Add code in curator.js read variant properties, shorten preferred name if it's too long, and display the name, or variation id if no preferred name, or other description if no variation id in curation-central page.
- Add code in variant-curation.js to display preferred name if existing in variant curation page.
=> Connects to #575 kl display variant preferred name

src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js
This PR is to add warning message on new family/individual curation pages, as well as to fix invisible individual label input field per Min's commit #3449215.
**Testing steps for #472**
1. Go to the GDM page and add a new PMID.
2. From the far-right column under "Evidence for PMID XXX", add a group curation by clicking on the blue Group bar.
3. Fill out the group curation form and add a family curation to the newly created group curation. And add an individual curation to the added family curation.
4. Upon completion, go back to the GDM page. Now click on the blue Family bar to add a new family curation, and on the curation page, you should expect to see a warning message above the "Family Label" input field stating "If this Family is a member of a Group, please curate the Group first and …
=> Connects to #472. Added warning message on new family/individual curation pages.

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**(This PR is to replace the closed PR #584, in which the committed changes incurred browser test failure and merge conflicts.)**
Following ticket #575, this ticket display ClinVar preferred title in curator palette and view pages.
**Changes**
- Add handling code to display preferred title in curator palette in curation central page
- Add handling code to display preferred title in family/individual/experimental view pages.
**Test Steps**
- Create GDM, add a PMID, add a new family, name Family010, enter variation ids 90973 and 9492, name proband Ind011, enter a Orphanet id, click Save. Go to curation central page and expect to see "Variants: 2" under Family010 and Ind011 in curator palette. And 2 preferred titles are shown in a pop-out window when mouse cursor is hover blue colored and …
=> Connects to #581. Variant preferred title.

src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js
The Assessment panel on Family and Experimental Curation pages should show up now on first load
Testing:
2. Create Experimental Data object
3. From Curation Central, click on View/Assess for the item, and ensure that the Assessment panel is visible on first load
4. Create Family object w/ Segregation data
4. From Curation Central, click on View/Assess for the item, and ensure that the Assessment panel is visible on first load
=> Connects to #593. Hidden assessment panel

src/clincoded/static/components/experimental_curation.js
Five Variants added to an Experimental Data object successfully, with forms interacting properly:
Make Variants un-editable after others have assessed on the Experimental Data object:
Testing:
2. Open up Add Experimental Data form
3. Add a bunch of variants and ensure that the fields interact properly, and a max of 5 variants can be added
4. Assess and Save Experimental Data object
5. Assess on same object w/ another user
6. Check the Edit page with original user, and ensure that the Variants cannot be changed as another user has assessed on the Experimental Data object
=> Connects to #596. Fix variant fields for multiple variants and make variants un-editable after multiple assessment

src/clincoded/static/components/curation_central.js
Verified with @wrightmw in person the behavior of the button.
Post-error:
After changing value the button is re-enabled:
Testing:
1. Create GDM
2. Open Add PMID modal
3. Test by attempting to add 0-filled PMID, non-numeric PMID, PMID w/ leading 0s, already-added PMID, and non-existent PMID (i.e. 999999999999999), and ensuring that the spinning cog disappears once the error appears. Changing the value in the form after the error should make the 'Add Article' button re-enabled
=> Connects to #602. Fix Add Article button on Add PMID Modal

src/clincoded/static/components/family_curation.js
This PR is to add the warning note below the *Individual Label* input field on the family curation page.
**Testing steps for #542**
1. Go to a GDM page and add a new PMID.
2. From the far-right *Evidence* column, click on the blue *Family* bar to proceed to the family curation page.
3. Scroll down the page and find the *Add variant associated with Individual* button. Click and add a variant.
4. Upon successfully adding a valid ClinVar ID, the Individual Label input field becomes visible. The warning note is expected to be present below the input field.
5. And this warning note should be the same as seen on the individual curation page.
=> Connects to #542. Added warning note below Individual Label input field on family curation page.

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_curation.js
* GDM breadcrumb displays properly on Variant Curation page
* GDM icon in Record Header points to proper PMID in GDM
Testing:
1. Create GDM, add multiple PMID
2. On non-first-created PMID, add Individual/Experiment/Family with Variant
3. Check Variant Curation page to make sure that the GDM links and display are correct
4. Check created Individual/Experiment/Family to ensure that the GDM link in Record Header points to correct PMID
=> Connects to #604. Revise breadcrumb display on Variant curation form

src/clincoded/static/components/experimental_submit.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/family_submit.js, src/clincoded/static/components/group_submit.js, src/clincoded/static/components/individual_submit.js
Fix inability to load Family Curation form after accessing the Edit Page of a Family that was already assessed
Testing:
2. Create Family w/ Segregation and Assess it
3. Assess it with another user
4. View Edit page for Family with original user
5. Go back to Curation Central
6. Click the 'Add Family' button and confirm that it takes you to the Family Curation page
Fix GDM Links in Record Header for Submit pages
Testing:
1. When creating items, make sure that the briefcase icon in the Record Header of the Submit pages are linked, and link to the correct record
Fix Individual information not showing up when adding variants on Family curation page
Testing:
1. Add Variants on Family Curation page. Confirm that the Individual information input fields show up.
=> Connects to #589. Family curation patch

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Text was fixed to 'VariationID' on Variant Curation page:
Text was also fixed to 'VariationID' on Family/Individual/Experimental Curation pages, on Other Description label:
Record header:
Record header w/ Assessment:
Palette:
=> Connects to #587, connects to #606, connects to #608. Text changes

src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/variant_curation.js
This PR is to address the "Cannot read property 'article' of null" error upon an user clicking on any of the individual/family/group/experimental name links in the header of variant curation page. Furthermore, this PR also removed some inline styles on the experimental curation viewer page.
**Testing steps for #616:**
1. Go to the curation central page and add a new PMID.
2. Clicking on the blue **Family** bar from the far-right **Evidence** column to proceed to the curation page.
3. Fill out the form and add a ClinVar ID and an individual associated with it.
4. Upon submitting the form and returning to the curation central page, click on the title of the variant in the **Associated Variants** panel to proceed to the **Curate Variant Information** Edit/View page.
5. Click on either one of …
=> Connects to #616. Fixed "Cannot read property 'article' of null" error.

src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/variant_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/static/scss/clincoded/modules/_form.scss
This PR is to address the problem in which the buttons are overlapping the text on the form submission confirmation page in narrow viewport.
**Testing steps for #539:**
1. Go to the Curation Central page and add a new PMID.
2. Proceed to the Family Curation page by clicking on the blue "Family" bar on the far-right column.
3. Fill out the form and click "Save" to submit it.
4. On the subsequent confirmation page, on where there are 3 buttons (e.g. **Edit proband Individual**, **Add non-proband Individual**, and **Return to Record Curation page**), reduce the browser window width to less than 767px.
5. You should expect to see that the buttons are no longer overlapping the text above it.
=> Connects to #539. Fixed button display in narrow viewport.

src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/variant_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR is to address the problem in which the **Mutalyzer** text is overlapping the line below it on the family curation page in narrow viewport.
**Testing steps for #612:**
1. Go to the Curation Central page and add a new PMID.
2. Proceed to the Family Curation page by clicking on the blue "Family" bar on the far-right column.
3. Scroll down toward the end of the form and click on the **Add variant associated with Individual** button to add a ClinVar VariantID.
4. Upon successfully adding a ClinVar VariantionID onto the form, reduce the browser window width to 1220px or less.
5. You should expect to see that the **Mutalyzer text** is no longer overlapping the line below it.
=> Connects to #612. Fixed text display in narrow viewport.

src/clincoded/static/components/experimental_curation.js
This PR is to address the persistent form submission error message next to the **Cancel** button at the bottom of the experimental curation page.
**Testing steps for #564:**
1. Go to the Curation Central page and add a new PMID.
2. Proceed to the Experimental Curation page by clicking on the blue **Experimental Data** bar on the far-right column.
3. On the subsequent form, select **Biochemical Function** from the **Experiment type** dropdown menu.
4. Then select option **A** from the **Please select which one (A or B) you would like to curate** dropdown menu.
5. Without filling out any other fields, click the **Save** button. You should expect to see the red **Please fix errors on the form and resubmit.** error message at the bottom of the form.
6. Scroll back up on the same form. Select …
=> Connects to #564. Clear error state when either experimentalType or experimentalSubtype selection is changed.

src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_curation.js
Fix display on Variant page for variants with Other Description specified
Add spacing between Mutalyzer text and orange box in Variant form
=> Connects to #587. Connects to #608. Display changes.

cloud-config.yml, src/clincoded/schemas/variant.json, src/clincoded/upgrade/variant.py
Testing:
1. Spin up AWS instance with production data
2. Confirm that variants have the `clinvarVariantTitle` field (filled in with a valid variant preferred title or empty string)
=> Connects to #635. Backfill clinvarVariantTitle field in variants

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/scss/clincoded/_base.scss, src/clincoded/static/scss/clincoded/modules/_curator.scss
Testing:
1. Add PMID with lower-case first-letter of last name (21217753)
2. Add PMID with upper-case first-letter of last name (19711971)
3. Confirm that sorting in the PMID list is case-insensitive
Testing:
1. Add Group, Family, Individual, Experimental Data, and Variants with very very long names
2. Confirm that the labels cutoff properly in the Curation Palette (both labels and associations), Variation Header, and Dashboard
=> Connects to #634. Connects to #638. Label styling, PMID sorting

src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/methods.js
**This PR is to address 2 issues:**
1. The edit form of Group/Family Method does not retain pre-existing data.
2. Suppressed form field labels/values in the viewer that have dependency on user's selection in experimental curation.
**Testing steps for #645:**
_Issue 1_
1. Go to Curation Central page and add a new PMID.
2. From the Evidence column on the far-right, click on the blue **Group** bar to proceed to the curation form.
3. Fill out the required fields, and particularly the entire section of **Group - Methods**. Submit the form and proceed with adding the associated family and individual curation. Please be sure to fill out the **Family - Methods** section for the family curation, and the **Country of Origin** in the **Individual - Demographics** section for the individual curation. …
=> Connects to #645. Edit form of Group/Family Method missing pre-existing data.

src/clincoded/schemas/experimental.json, src/clincoded/schemas/family.json, src/clincoded/schemas/group.json, src/clincoded/schemas/individual.json, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/experimental_submit.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/family_submit.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/group_submit.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/individual_submit.js, src/clincoded/static/libs/bootstrap/form.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
* Add support for `maxLength` for text fields in `form.js`
* Implement `maxLength` into label fields on curation pages
* Fix/better CSS for long label names on curation, submit, and view pages
* Changes to schema to enforce max label length
Testing:
2. Add Group, Family, Individual, and Experimental Data objects with various nesting, and verify that the maximum name for these is 60 characters at most
3. Check the edit, submit, and view pages, along with the curation palette, at very window widths, and ensure that the ellipsis and rendering of the rest of the page is correct
* CSS class changes to buttons
Testing:
1. Create GDM, add PMID, create family
2. Re-size resulting submit page to make sure that the buttons scale properly
=> Connects to #640. Connects to #647. Label length limit and briefcase fix

cloud-config.yml, cloudwatchmon-requirements.txt
Included in PR:
--Set up AWS sns notifiers for different condition that might need attention (on AWS, not in code changes here). Current topics are: AWS-alert-Memory-usage, AWS-alert-CPU-usage, AWS-alert-Status-Check
--Add cloudwatchmon package to send stats to AWS
--Method for setting alerts from commandline for instances of interest (prod/test)
--Change reboot time to 01:00 for unattended upgrade reboots
To stress test a t2.medium instance that has the alarms set:
`sudo apt-get stress`
CPU OVERLOAD (t2.medium instance):
`stress -c 2 -i 1 -m 1 --vm-bytes 128M -t 600s`
MEMORY OVERLOAD (t2.medium instance):
`stress -m 2 --vm-bytes 3G -t 600s`
Setting alerts from the commandline (should be made into a script using boto in a subsequent ticket):
`aws cloudwatch put-metric-alarm --alarm-name …
=> Connects to #343 AWS cloud monitoring and package upgrade configs

src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js
Editing an Individual now refreshes the Variants list from the Individual before saving.
Testing:
2. Create Family + Variant + Proband via the Family curation page
3. Open Edit Proband/Individual page in new tab/window
4. Open Edit Family page in another tab/window
5. Make changes to Variant associated w/ Proband in Edit Family page
6. Make changes to Proband/Individual in its Edit page
7. Curation palette should display correct variants for both Family and Individual
Added label limit length to Individual Label field in the Family page when adding proband
Testing:
2. Create Family + Variant + Proband, and specify a very long name for the Proband label
3. Confirm that the Proband label length is limited to 60 characters, and you can create a …
=> Connects to #660. Connects to #640. Variant list refresh and Label limit

src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR is to address the offset (or vertical alignment) of *Associations* link text in curation palettes.
Steps to test #659 
1. On the Curation Central page, create a new PMID.
2. Then proceed with creating a new Group evidence, along with associated Family and Individual evidences, as well as with associated variants.
3. Complete and submit all the forms to return to the Curation Central page.
4. In the curation palettes, expect to see the *Associations* link text are vertically aligned to the baseline of the word **Associations** in the various curation palettes.
=> Connects to #659. Link text offset in curation palettes.

src/clincoded/schemas/variant.json, src/clincoded/tests/data/inserts/variant.json, src/clincoded/upgrade/variant.py
Change in schema:
1. Added a new property "carId" to store CAR id.
2. Changed type of "dbSNPId" and "clinvarRCV" to array for storing multiple values.
3. Changed type of "hgvsNames" to object for storing terms of RGCh37, RGCh38 and others separately.
4. Added a new property "clinvarSCVs" for storing ClinVar SCV ids in feature.
Change in test data:
1. Added CAR ids in variant 55962, 55964, 55966 and 55996.
2. HGVS terms were reformed as: {"gRCh37": "....", "gRCh38": "....", "others": ["...", "..."]}
View sample:
go to ../variants and select 55962, 55964, 55966 or 55996
Test instance with production data: https://676-kl-edit-variant-schema-ca40197-kangliu.demo.clinicalgenome.org
=> Connects to #676 kl edit variant schema

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/select_variant.js
New variant modal 'Save' button on select variant page:
Pressing the 'View Variant' button here should create the variant object then take you to `/variant-central/?variant=[UUID]` (page not yet implemented)
Removed a lot of code from `select_variant.js` page involving rendering of returned variant data from modal.
=> Connects to #681. Forwarding from select variant page

src/clincoded/static/components/curator.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Test with ClinVar IDs 9492 and 90973 (or CA ID CA212917)
Long HGVS terms should ellipsis properly.
=> Connects to #685. HGVS term wrapping

.gitignore
To prevent inadvertent additions of compiled and versioned css files `.gitignore` was modified.
Changed: 
`src/clincoded/static/css/bootstrap.css`
`src/clincoded/static/css/responsive.css`
`src/clincoded/static/css/style.css`
To:
`src/clincoded/static/css/`
To test:
From commandline: 
- run `bin/buildout -c buildout-dev.cfg`  or `bin/buildout` as usual
- use `git status` command
Result:
-  You should no longer show the compiled css directory `src/clincoded/static/css/` in the git `Untracked files` list
=> Connects to #694 ignore compiled and versioned css

src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/mapping/SO_term.json, src/clincoded/static/libs/parse-resources.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR consists of changes pertinent to Issue #672.
1. Added a JSON mapping file (e.g. SO_term.json) consisting of **SO term** and **SO id** pairs. The list of mapping pairs are taken from http://uswest.ensembl.org/info/genome/variation/predicted_data.html#consequence_type_table
2. Created a new "mapping" sub-directory in the anticipation of more mapping files being required, such as NM-to-NC and NM-to-EN.
1. The sortable "All Transcripts" table columns have not yet been implemented (as requested in https://github.com/ClinGen/clincoded/issues/672#issuecomment-223381387).
2. The RefSeq transcripts have not been merged into the "All Transcripts" table with the Ensembl transcripts (as requested in …
=> Connects to #672. VCI Basic Information Tab UI.

src/clincoded/static/components/globals.js, src/clincoded/static/components/select_variant.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js
Connects to #704:
* When switching between tabs, the URL should update with the proper `tab` value in the URL query string for the tab you switched to
* When switching to the basic info tab, the `tab` query should be removed from the URL. But manually navigating the basic info tab by appending `&tab=basic-info` to the URL should still work
* When reloading or navigating directly, if a tab is specified via a the `tab` query in the URL, that particular tab should be loaded
Connects to #701:
* Confirm correct button text:
=> Connects to #704. Connects to #701. Tab info appended to URI. Change modal button name

src/clincoded/static/components/variant_central/interpretation/population.js
This PR is to address the issue in which clicking on the Population tab does not invoke data fetching if the default tab (e.g. selectedIndex={0}) is the Basic Information tab.
Since the default tab is normally set to 0 (e.g. selectedIndex={0}), when the page loads, the "Basic Information" tab receives the props and invokes fetching. When clicking on other subsequent tabs, fetching is not invoked because the props had been received.
So as a temp hack for the population tab development, I set to the selectedIndex to 1 for two reasons: 1) it defaults to the population tab every time the page is refreshed (so it saves a click each time during debugging; 2) it fetches data immediately after the page refresh.
By confirming that each time clicking on a tab incurs the …
=> Connects to #683. Added lifecycle method to invoke data fetching for Population tab.

Gruntfile.js, Makefile, package.json
- `bin/grunt dev` - watch for js and scss changes and browserify bundle minimal js files or compass compile  
- `make clean-css` - clean all compiled style.css and versioned style files
- `make clean-js`  - remove all previous browserify compiled js files and versioned bundle files
Added npm packages:
- grunt-contrib-compass
- grunt-contrib-watch
Removed npm package:
- watchify
**TO USE:**
- Run `bin/buildout -c buildout-dev.cfg` at least once to get the additional npm packages if you don't run it regularly
- Run `bin/grunt dev` to watch js and css changes. This will also remove the dependency on versioned files (i.e. you must run this command *at least one time* to set the js bundle to point to an unversioned style.css even if you want to use `bin/compass compile` separately)
**Browser …
=> Connects to #653 Dev tooling -- grunt watch for js and css compile, mods to "make" command

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/select_variant.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/functional.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/segregation.js, src/clincoded/static/libs/parse-resources.js
**Related to #726:**
* Extract URLs in curation pages out to globals
* Update URL builders so they use http or https protocols depending on context
**Misc:**
* Add `FIXME` comments to temporary form code
* Rename `parseClinvarMixin` to `parseClinvarExtended` since 'Mixin' is a reserved nomenclature in React
**Demo instance:**
https://726-mc-httphttps-aeb8562-minchoi.demo.clinicalgenome.org/
(A commit or two behind, but the commits are adding comments so should not have any functional impact)
**Testing:**
1. Create Variant via VCI (both via ClinVar ID and CA ID)
2. Confirm that the external data gathering works on https protocol for basic info and populations tab
**Caveats:**
* CAR is still half-working at best due to fake certificates
* Still lots of errors on rendering
* I think global's …
=> Connects to #726. Use globals for external URLs; support http/https protocol switching

src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/population.js
Test instance: http://732-mc-population-tab-try2.instance.clinicalgenome.org/
* Re-structured `populationObj`
* Updated the parsers to support new model
* Revised rendering of tables to use loops
* Re-implemented 1000G parser
* Connected `populationObj` to evaluation/assessment forms
Testing:
1. Load variant (tested with 139214, 139215)
2. Check population tab for proper rendering and linkouts of data
3. Create interpretation and save it
4. Confirm that the interpretation has saved properly, and the interpretation evaluation evidence is also saved properly
Caveats/To-Do's:
* ~~When navigating away from the VCI page, a bunch of `setState` errors pop up. Maybe a separate ticket:~~
* Fixed as of commit 57b85e1 - test by loading VCI, then pressing the Header image to go to dashboard. Console …
=> Connects to #732. Population tab

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/select_variant.js, src/clincoded/static/scss/fontawesome/_icons.scss
ClinVar modal:
CAR modal with ClinVar data:
CAR modal with no ClinVar data:
Testing:
1. Add variant via VCI, via both ClinVar and CA IDs
2. Check that ClinVar and/or CA IDs display and link out properly
Testing:
1. Load select variant page in VCI and check console logs
2. Load Family/Individual/Experimental curation pages and check console logs
=> Connects to #700. Connects to #742. Add Variant ID display to VCI modal results. Fix console errors.

src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js
**Changes** in dir `src/clincoded/static/components/`
Replaced "uuid" with "@id" to get variant object in files `family_curation.js`, `individual_curation.js` and `experimental_curation.js`
No changes in schema and test data.
**Test Steps**
1. Create a GDM,
2. Add a PMID (any one, e.g. 123),
3. Add a new experimental (Expression, B Altered Expression in Patients), and associate a variant (e.g. ClinVar ID 12345) and click Save. Expect to see an experimental object added successfully.
4. Edit the experimental, associate another variant (e.g. 12346) and click Save. Expect to see the second variant associated to the experimental.
5. Add a family, enter ORPHA number (e.g. ORPHA15), associate a variant (e.g. 55962), enter a proband individual label and ORPHA number, and click Save. Expect to …
=> Connects #741 kl Bug associate variant

src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js
This PR consists of changes pertinent to addressing data not being displayed on the Basic Info tab initially upon the user navigating from the variant selection page.
1. In the related ticket #731, the intent is to address the looping of page reloads when the user deliberately refreshes the VCI hub page repeatedly. What has been discovered is that, if the time between each page refresh is longer than 2-3 minutes, the looping does not incur. The looping issue, which incurs when the page is refreshed within a few seconds after the prior refresh, is suspected to be pertinent to external API calls that needed time to complete. Due to shifting priority to the implementation of "static" evidence criteria bar (above the tabs) for the VCI interface, this looping issue will be …
=> Connects to #731. Basic Info tab update.

src/clincoded/schemas/computational.json, src/clincoded/schemas/evaluation.json, src/clincoded/schemas/interpretation.json, src/clincoded/schemas/population.json, src/clincoded/schemas/variant.json, src/clincoded/types/__init__.py
This PR corrects errors issued in ticket #744, including failed to display interpretation/evaluation/population/computational objects, wrong type of a couple of properties and unnecessary calculated properties.
**Changes in schema Files** in dir `src/clincoded/schemas/`
1. Replaced columns property "variant.represent" with "variant.variant_identifier" in file `computational.json`, `evaluation.json`, `interpretation.json` and `population.json`.
2. Added columns property "variant.source" and changed type of columns properties "evaluation_count" and "provisional_count" to number in file `interpretation.json`.
**Changes in File** `src/clincoded/types/__init__.py`
1. Edited calculated properties "Evaluations", "Provisionals" and their functions to match the changes in schema files.
2. Removed …
=> Connects to #744 kl load interpretation, evaluation, population and computational

src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/criteria.js, src/clincoded/static/components/variant_central/interpretation/mapping/evidence_code.json, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR consists of changes pertinent to implementing a _"static"_ criteria bar above the tabs for the test alpha release.
The _"static"_ criteria bar is not a functional UI. It is meant to show the intended functionality in the demo. 
For the time being, I just followed the color scheme for the different groupings of codes as shown in the ACMG diagram. For example, **purple** is for "benign-strong" (BS) and **blue** is for "benign-supporting" (BP), and so on and so forth.
1. The _solid_ colored criteria codes indicate the use case in which it has been associated with disease and has been evaluated.
2. The _white_ with colored text criteria codes indicate the use case in which it has been associated with disease but has not been evaluated.
3. The …
=> Connects to #749. Static criteria bar for test alpha release.

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/select_variant.js, src/clincoded/static/components/variant_central/header.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Select page:
Modal:
Hub:
Testing:
1. Load select variant page. Confirm warning text.
2. Open CA ID modal. Confirm warning text in modal.
3. Add CA ID that does not have a grch37 info (ex: CA034913). Confirm warning text in hub.
4. Add CA ID/ClinVar ID that does have grch37 info. Confirm warning text does not exist in hub.
=> Connects to #754. grch37 warnings

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/header.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Test instance: http://767-mc-population-linkouts-try2.instance.clinicalgenome.org/ - few commits behind, but most functionality is in.
Link out to ExAC's gene page for the Constraint Score section, if the gene info is available.
Testing:
1. Add variant w/ GRCh37 data, confirm that ExAC Constraint Score section is visible, and that link is correct
2. Add variant w/o GRCh37 data, confirm that the section does not appear
Update the link outs from the population tables. Different links out if it has data or not. Updated text and location of these linkouts.
With data:
Without data:
Testing:
1. Add variant w/ various population data availability (139214, 66756, 41231)
2. Confirm that linkouts are correct
The 1000 Genomes parser now grabs the ref and alt allele information from the NC value, …
=> Connects to #750. Connects to #767. Connects to #781. Connects to #783. Population tab changes

src/clincoded/static/components/variant_central/record_variant.js, src/clincoded/tests/data/inserts/variant.json
This PR is for tickets #746 and #779 about displaying ClinVar variation id, CAR id, dbSNP id and their links to specific pages in external sources.
**Test**
* In Select Variant page, select ClinVar Variation ID and enter 55966, retrieve data and Save. Expect to see:
* Click link at 55966, expect to go to http://www.ncbi.nlm.nih.gov/clinvar/variation/55966/
* Click link at CA144043, expect to go to http://reg.genome.network/allele/CA144043.html
* Click link at rs386833448, expect to go to http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=386833448
* Back to dashboard and go to Select Variant page
* Select ClinVar Variation ID and enter 139214, retrieve data and Save. Expect to see:
* Back to dashboard and go to Select Variant page
* Select ClinGen Allele Registry ID and enter …
=> Connects to #779, Connects to #746. ids and links in header

src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/mapping/NC_genomic_chr_format.json, src/clincoded/static/components/variant_central/interpretation/population.js
This PR consists of changes pertinent to the Basic Info tab in addressing the following:
* Remove IDs (e.g. ClinVar Variation ID, dbSNP ID) from top of basic information tab since they are already displayed in the static header.
* Change the title of the first table from "Primary Transcript" to "ClinVar Primary Transcript".
* If a variant is not in ClinVar then put "No data was found for this allele in ClinVar. Search ClinVar for this variant." in this table.
* For now, add a table with a list of non NC_ hgvs names obtained from RefSeq if the variant is in ClinVar.
* Comment out "non-functional" Uniprot ID at the bottom of the tab temporarily.
* In the Ensembl transcript table, use the GRCh38 hgvs notation in the API call instead of the rsID to only obtain the relevant allele transcripts. …
=> Connects to #782. VCI Basic Info tab updated changes.

src/clincoded/static/components/variant_central/title.js
The final decision is set as following order:
* display ClinVar preferred title for any ClinVar variant,
* display NC_ genomic GRCh38 for any non-ClinVar variant if it has NC_ HGVS GRCh38,
* display CAR id, otherwise
**Test**
* In Select Variant page, select ClinGen Allele Registry ID, enter CA144043 (this is ClinVar varaint), Save. Expect to see
* Go back to Select Variant page, select ClinGen Allele Registry ID, enter  CA501058 (this variant has no ClinVar data but a NC_ HGVS), Save. Expect to see
* Go back to Select Variant page, select ClinGen Allele Registry ID, enter CA501064 (this one has neither ClinVar data no NC_ HGVS). Expect to see
**End Test**
=> Connects to #760 kl non clinvar title

src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/shared/form.js, src/clincoded/static/libs/bootstrap/form.js, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/static/scss/clincoded/modules/_form.scss
Instance: http://737-mc-calculate-ci-2374fe1-minchoi.instance.clinicalgenome.org/
* CI fields only show up when interpretation is added
* CI lower and upper values update when desired CI is changed
* Clearing the the desired CI field or putting in bad characters will default the value to 95 on clicking away
* Desired CI values are saved on evaluation form saving, and is pre-filled with saved value on re-loading the interpretation
*Testing:*
1. Get to VCI hub, populations tab
2. Add interpretation and confirm that the CI fields now show up, with 95 as default value
3. Change Desired CI to confirm that upper and lower values change correctly (check against Steven's Excel spreadsheet)
4. Put bad characters into field, confirm that value defaults to 95 when clicking away from text box
5. Save …
=> Connects to #737. Connects to #788. Calculate CI and standardize decimal places on pop tab

src/clincoded/static/components/variant_central/header.js, src/clincoded/static/components/variant_central/interpretation/criteria.js, src/clincoded/static/components/variant_central/title.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**Changes:**
- Extended off of 765_kl_CalculatePatho_button branch to fix some UI components.
- Adds temporary/non-functional "Calculate Pathogenicity" after VCI Interpretation mode has started
- Add visual cues to Features in Development (yellow border on left)
- Fixed some eslint errors in `/src/clincoded/static/components/variant_central/interpretation/criteria.js`
***
**To Test:**
VCI
- +  "Select Variant" -> choose CAR or CA ID pathway
- +  "Start new interpretation"
- Check UI changes
- "Calculate Pathogenicity" should appear in the header and have a yellow UI border on the left
- Bar of criteria codes should have yellow UI border on the left
***
**Re-usable UI implementation:**
Note: This ticket will include the addition of a generalize-able UI designation to denote a …
=> Connects to #765  Calculate Pathogenicity temp button and Feature in Dev UI

src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/libs/parse-resources.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR consists of changes pertinent to the UI of computational tab.
1. The data in the "ClinGen Predictors" table is static at the moment. Will add logic to call the API (e.g. https://predictvar.bustamante-lab.net) after today.
2. Removed the placeholder external links in the "Repetitive Region" section for future implementation as they are low-priority. But the header of "Repetitive Region" is left in the code in case @mrmin123 needs it in the process of implementing the form. He can choose it to remove it or hide it together with the form.
3. Just discovered that not all ClinVar IDs (e.g. 139214) returns the <ProteinChange> node in its Eutils API response. Currently there is no logic to bypass it and thus rendering bails out due to error. Will add logic to fix this …
=> Connects to #718. Connects to #776. VCI Computation tab.

src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/shared/form.js, src/clincoded/static/libs/bootstrap/form.js
* Default value is 5
* If user clicks away and there is invalid/blank value, it defaults to 5
* Value is saved into `populationObj`
* Value is loaded and pre-populated on evaluation load
Testing:
1. Get to VCI, population tab
2. Create interpretation
3. Confirm that MAF cutoff field is pre-populated with 5
4. Change MAF cutoff field, save evaluation. Confirm that the proper value is stored in interpretation's evaluation's population's populationData's mafCutoff field
5. Try changing MAF cutoff field (including blank and bad values), and confirm that the field is properly updated
=> Connects to #777. MAF cutoff field in population tab

src/clincoded/static/components/variant_central/actions.js, src/clincoded/static/components/variant_central/index.js
It's required to stay at same tab after click "Start new interpretation" button.
**Changes**
Added codes in file `src/clincoded/static/components/variant_central/actions.js` to pass tab info to new page.
**Test**
* After select variant id type, enter variant id and get into initial variant-central page, select any tab and click "Start new interpretation" button. Expect to see new interpretation page stays at the same tab.
=> Connects to #789 kl stay on same tab

src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/shared/form.js, src/clincoded/static/libs/bootstrap/panel.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
* Computational eval forms are in
* Collapsible panels for both population and computational tabs
* CSS updated for wider content area in tabs
* CSS updated so that tabs and panel css names do not collide
* `form.js` updated to remove form title and Panel groups; these were moved to their respective tabs
Population tab w/ Interpretation:
Predictors tab w/ Interpretation:
Testing:
1. Get to VCI, w/ no interpretation
2. Check population tab, check that panel displays and collapses properly
3. Check predictors tab, check that panels display and collapse properly
4. Add interpretation
5. Check population tab, check that form + data displays and collapses properly
6. Check predictors tab, check that forms + data displays and collapses properly
7. Check evaluation forms and output data in …
=> Connects to #769. Computational eval forms. Collapsible groups.

src/clincoded/static/components/variant_central/interpretation/functional.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/components/variant_central/interpretation/segregation.js, src/clincoded/static/components/variant_central/record_curator.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR is for 2 requirements.
1. Adding text messages to non-function tabs (Functional, Segregation and Gene-specific).
2. Remove links "View" and "Edit" to interpretation object in header.
**Code Changes**
1. Added text message related codes in files `functional.js`, `gene_specific.js` and
`segregation.js` in dir `src/clincoded/static/components/variant_central/interpretation/`.
2. Removed codes related to "View" and "Edit" links in file `src/clincoded/static/components/variant_central/record_curator.js` and removed background color related codes in file `src/clincoded/static/scss/clincoded/modules/_curator.scss`.
**Test**
* Select ClinVar Variation ID and enter 55962. In variant-central page, expect not to see "View" and "Edit" links in header.
* Select tab "Functional", expect to see …
=> Connects to #771 kl note for non function tab

src/clincoded/static/components/variant_central/actions.js, src/clincoded/static/components/variant_central/header.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/record_curator.js, src/clincoded/static/components/variant_central/title.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR consists of changes pertinent to #759, #761 and #770.
1. Currently, after the modal is closed upon associating the interpretation with disease, the disease id/term is not immediately reflected in the interpretation record slugline under "My interpretations" in the static header. Refreshing the page would invoke the disease id/term to be displayed.
2. After merging with the latest `dev`, I noticed that the criteria bar now wraps to a second line when the interpretation is active.
1. Login and enter ClinVar ID 55980 via the variant selection interface.
2. In the evidence only view, expect to see the "Start new interpretation" button when there is not associated interpretation.
3. Proceed to the "Population" or "Predictors" tab, click on the …
=> Connects to #759. Connects to #761. Connects to #770.

src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/shared/form.js, src/clincoded/static/libs/parse-resources.js
* Fix typo in BA1 label
* Add conditionals to `parseClinVarExtended()` `protein_change` parser, as well as computational tab parsers that relies on this `protein_change` field
* Switch form and table order for computational tab's 'Variant in Same Codon' section
* Update `form.js` to check for disease in `componentWillReceiveProps`; forms properly become activated when disease is added without refresh
=> R7Alpha1 bugfixes and tweaks

src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/record_gene_disease.js
This PR is for tickets #807 (use external_url_map in `globals.js`) and #809 (Bug: wrong context links for variants in chr 10 and chr 20).
**Code Change for Fixing Bug**
* Edited code to set chromosome from NC_ HGVS terms in file `src/clincoded/static/components/variant_central/record_gene_disease.js`
**Code Changes for Using external_url_map**
* Added urls in module "external_url_map" in file `src/clincoded/static/components/globals.js`.
* Replaced inline urls with external_url_map module in file `src/clincoded/static/components/variant_central/record_gene_disease.js`
**Test Steps**
1. Select ClinVar Variation ID 24 (chr 10) or 157 (chr 20), Save. 
2. Click each Context links. Expect to open relevant page.
=> Connects to #807 use external_url_map, Connects to #809 bug: wrong context links

src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/shared/externalLinks.js, src/clincoded/static/components/variant_central/record_gene_disease.js
It's required to display variant context links in the bottom of Basic Info tab and Predictors tab.
**Code Changes** in dir `src/clincoded/static/components/variant_central/interpretation/`
1. Created a module function to set context links for GRCh38 and GRCh37 NC_ HGVS terms in file `shared/externalLinks.js`
2. Edited codes to use the module in file `record_gene_disease.js`.
3. Added the same codes to files `basic_info.js` and `computational.js`.
**Test**
* Select ClinVar Variation ID, enter 139214, click Save. Expect to see context links in Basic Info tab as:
* Click Predictors tab and expect to see:
* Click each link and expect to open relevant page.
**End Test**
=> Connects to #806 kl copy context links

src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/title.js
⬇️ 
⬇️ 
Testing:
1. Get to VCI
2. Check text in title bar
3. Add interpretation
4. Check text in title bar
5. Add disease
6. Check text in title bar
Also check that the 'See data in ExAC' link in population tab works properly (addresses bug report in #767)
=> Connects to #814. Disease subtitle handling in titlebar

src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**This PR consists of changes pertinent to the following changes:**
1. For really really long HGVS terms displayed in the Genomic panel on the "Basic Info" tab, ellipsis has been applied to the terms width equals to the width of the panel.
2. For really long HGVS terms displayed in the Ensembl Transcripts table on the "Basic Info" tab, ellipsis has been applied to the terms width equals to the width of the table column.
3. Added CSS rules to fix the wrapping issue on the static criteria bar.
Steps to verify:
See screen shots attached in https://github.com/ClinGen/clincoded/issues/812.
=> Connects to #812. Fixed clipped long hgvs terms and criteria bar wrapping.

src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
* Separate out css for bootstrap callouts to retain styling differences between two tabs:
=> Separate callout CSS between tabs

src/clincoded/static/components/variant_central/interpretation/population.js
* Convert `parseFloatShort()` from a data parser method to a render method
* Data parsers now use `parseFloat()`, while rendering methods now use `parseFloatShort()`
* Stored data is now the large, un-rounded float, as calculated or received from external resource
* On display, the floats are rounded down to 5 digits. If the value has more than 5 decimal places, leading 0s are added when applicable (including numbers nearing 0, which will show as 0.00000); if the value does not have more than 5 decimal places, it does not show trailing 0s (a flat 0.5 will be 0.5, a flat 0 will be 0, etc)
If the # of digits is > 5, it shows 5 digits (numbers nearing 0 will be shown as 0.00000)
If the # of digits is less than 5, no additional trailing 0s are added, as with 1000G EUR below:
Testing:
* …
=> Connects to #826. Better float handling in population tab

src/clincoded/static/components/variant_central/interpretation/computational.js
This PR consists of change pertinent to address the wildcard search in finding neighboring variants.
1. The wildcard "asterisk" has been removed from the following URL construct:
`dd>(<a href={external_url_map['ClinVar'] + '?term=' + codon.term + '*+%5Bvariant+name%5D+and+' + codon.symbol} target="_blank">See data in ClinVar <i className="icon icon-external-link"></i></a>)</dd>`
1. Login and enter the 53423 ClinVar ID at the variant selection page.
2. Proceed to the computational tab and scroll down to the "Variants in the Same Codon" section.
3. Expect to see that there is a "5" for the "Number of variants in codon" label.
4. Examine the linkout and expect to see the wildcard asterisk no longer present in the URL (e.g. …
=> Connects to #832. Removing asterisk/wildcard in Entrez codon search.

src/clincoded/static/components/variant_central/actions.js
This PR consists of change pertinent to show progress indicator (e.g. spinning gear) in the "Associate with Disease" modal's "OK" button upon user's click event.
1. Login and enter 53423 ClinVar ID on variant selection page.
2. Proceed to evidence pool only interface and click on the "Start New Interpretation" button.
3. Upon the appearance of the "Associate with Disease" button, click on it and invoke the modal.
4. Enter ORPHA777 and click on the "OK" button. Expect to see the button to be in "disabled" mode with a "spinning gear" in it momentarily before the modal is closed.
5. This behavior should be consistent even when user edits disease (e.g. ORPHA891) via the same modal.
=> Connects to #835. Added button progress indicator.

package.json, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/record_curator.js
This PR consists of changes pertinent to removing the react-localstorage npm package and references to this npm package.
The react-localstorage npm package is no longer used in the VCI app.
1. Remove any pre-existing local storage objects in Chrome, by going to Chrome DevTools and selecting "Resources" in the menu bar. Then from **"Local Storage"** in nav bar on the left, select "http://localhost:6543" and particularly remove the `CurationRecordCurator` object if it exists.
2. Login and enter the 139214 ClinVar ID via the variant selection interface.
3. Upon arriving at the evidence only view of the VCI, check the **"Local Storage"** in Chrome DevTools again. Expect to see that the VCI app no longer stores the `CurationRecordCurator` object.
=> Connects to #790. Remove react-localstorage npm.

src/clincoded/schemas/evaluation.json, src/clincoded/schemas/provisionalClassification.json, src/clincoded/tests/data/inserts/evaluation.json, src/clincoded/types/__init__.py
This PR fixes 2 bugs (failed to use #!edit-json and failed to display provisional classification objects) and corrects 1 schema-related mistake (incorrectly named a property as "description", details in ticket #856).
**Bug 1: Failed to use #!edit-json**
* Reason:  Reverse link as a calculated property should be type of array. Incorrectly set as string or object in some objects including evaluation, population and computational cause failed .
* Code Change: Correct type for all reverse links with wrong type setting in file `src/clincoded/types/__init__.py`.
* Test Sample (evaluation)
- Go to to [http://localhost:6543/evaluations](http://localhost:6543/evaluations), select one and add `#!edit-json` at the end of url, return. Change `"criteria"` value to "AAA" and click Save. Expect to see: …
=> Connects to #856 kl bug edit json

src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/shared/form.js
Replaces all instances of 'description' in the VCI evaluations form/UI to 'explanation'. All forms tested w/ code from branch `856_kl_bug_edit_json` (PR #856) merged in.
Testing (note: requires code from above branch to work):
1. Get to VCI hub, add interpretation, add disease (optional)
2. Fill out and hit save on all evaluation forms in population and computational tabs
=> Connects to #858. 'description' -> 'explanation' in VCI eval forms

src/clincoded/static/components/variant_central/helpers/hgvs_notation.js, src/clincoded/static/components/variant_central/helpers/primary_transcript.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation/computational.js
This PR consists of changes pertinent to the handling of UI display in the variant codon table on the computational tab.
1. Abstracted the repetitive code from index.js and created a helper method to get HGVS notation in the formats required by either myvariant.info or Ensembl VEP.
2. Created a helper method to set the primary transcript based on the logical filtering of properties such as 'canonical', 'source' and 'hgvsc' in the Ensembl VEP response.
3. Added '&canonical=1&merged=1' params to Ensembl VEP API request to expose **canonical** flags and **RefSeq** transcripts in response.
4. Decoupled the Eutils/Esearch combo fetch method since the Esearch method for codon data relies on Ensembl VEP response going forward.
5. Updated the handling of UI display in the …
=> Connects to #827. Codon data display.

src/clincoded/static/components/variant_central/interpretation/computational.js
This PR consists of changes for adding (static) table rows for HumanSplicingFinder and removing GeneSplicer linkout in the "Splice Site Predictors" table.
1. Login and use 55847 at the variant selection interface.
2. Proceed to the Predictors tab and scroll to the **Splice Site Predictors** table.
3. Expect to see the GeneSplicer external link no longer exists.
4. Expect to see additional 4 **HumanSplicingFinder** table rows adding to the table.
=> Connects to #862. Splicing table update.

src/clincoded/static/components/variant_central/interpretation/shared/form.js
This PR fixes bug that "Stand alone" option doesn't result expected change in progress bar and removes option "stand alone" from pulldown list of BA1 selection(ticket #890).
**Code Change** in File `src/clincoded/static/components/variant_central/interpretation/shared/form.js`
1. Added element "stand-alone" in an array that containing all modified values in file.
2. Edited condition to filter out option "stand alone" from BA1 criteria 
**Test**
* In VCI, enter a variant id, click Start New Interpretation button and go to Population tab, 
1. Change BS1 selection to option "BS1_stand alone" and click Save. Expect to see changes in progress bar as:
2. Click criteria BA1 selection and expect not to see "BA1_stand alone" in pulldown list.
=> Connects to #890 bug stand-alone option not work

src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/helpers/hgvs_notation.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/libs/parse-resources.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR consists of implementations pertinent to the change requests in constructing the external ExAC linkout differently when there is no ExAC population data is found for the table display on the Population tab.
1. In the `hgvs_notation.js` and `parse-resources.js` files, I added "if" statements to several places to ensure script execution even when the expected data is absent in the REST API response.
2. In the `basic_info.js` file, removed no-longer-used code and refactored code to ensure script execution even when the expected data is absent in the REST API response.
1. Login and use **53981** and/or **90973** for selecting a variant (relevant to #885).
2. Expect to see that the long HGVS terms are ellipsis and not pushing the table beyond …
=> Connects to #846. Connects to #885.

.eslintrc.json, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/shared/credit.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR consists of implementation pertinent to adding UIs for crediting external data sources such as myvariant.info and VEP.
1. Login and select 55962 variant id.
2. On the Basic Info tab, expect to see the "VEP" icons next to the headers of **RefSeq Transcripts** and **Ensembl Transcripts** tables. Expect to see the "VEP" credit at the bottom of the page.
3. On the Population tab, expect to see the "MVi" icons next to the headers of **ExAC** and **ESP** tables, and the "VEP" icon next to the header of **1000 Genomes** table. Expect to see the "MVi" and "VEP" credits at the bottom of the page.
3. On the Predictors tab, expect to see the "MVi" icons next to the headers of **Other Predictors** and **Conservation Analysis** tables. Expect to see the "MVi" credit at the …
=> Connects to #800. External data source crediting.

src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/shared/calculator.js, src/clincoded/static/components/variant_central/title.js
**This PR is related to:**
1. Ticket #895 to fix bug that search links in Population were not opened in new tabs and removes unnecessary extra space under Start New Interpretation button.
2. Ticket #897 to change text of "Calculate Pathogenicity" button to "View Summary" in title area.
**Code Changes for ticket #895**
* Edited `<a>` tag for opening linked page in new tab in file `src/clincoded/static/components/variant_central/interpretation/population.js`.
* In files `src/clincoded/static/components/variant_central/interpretation.js` and `src/clincoded/static/components/variant_central/interpretation/shared/calculator.js`, edited `<div>` tag to remove space under Start New Interpretation button.
**Code Changes for ticket #897**
* Changed text of `<button>` tag to "View Summary" in file …
=> Connects to #895 links in new browser tab, Connects to #897 View Summary button

.eslintrc.json, src/clincoded/tests/data/inserts/user.json
Devs noticed that eslint was not reporting (or mis-reporting) JS errors:
--updated `.eslintrc.json` to similar version used by encoded
Also, additional users added:
--new curators
--test curators
**NOTE**
Devs: You should `npm upgrade` to the current version of these packages:
`npm upgrade -g eslint`
`npm upgrade -g eslint-plugin-react`
Devs: Please verify that Sublime (or your editor of choice) can use and report linting errors/warnings for eslint (JS) errors and flake8 (Python) errors
=> Connects to #899 eslint plus users

src/clincoded/static/components/variant_central/actions.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js
Parameters in VCI URL should behave better now:
* When starting an interpretation with a subtab, the tab value is no longer replaced with the subtab value
* When starting an interpretation with a subtab, the user should be taken back to where they began the interpretation
* Passing invalid keys to the tab parameter defaults you to the basic-info tab, instead of displaying nothing
* Passing invalid keys to the subtab parameter defaults you to the missense subtab, instead of displaying nothing
Testing:
* Test above conditions in VCI
Updated the `parseAlleleFrequencyData` method in `population` tab to not store `NaN`s. These `NaN`s were being stored as `null`s in the database, and `find_diff` were flagging them as differences in UI.
Testing:
* Add variant w/ no ExAC data (41312)
* Add …
=> Connects to #908. Subtab parameter on interpretation start

src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/components/variant_central/interpretation/shared/credit.js
This PR primarily consists of changes pertinent to:
1) Fixing the bug in which the Ensembl link does not persist if the user navigates to other tabs and returns to the Gene-centric tab (#903).
2) Adding the list of synonyms under **HGNC** in the Gene Resources panel on the Gene-centric tab (#904).
Additional changes:
1) Fixing a bug that causes script execution and UI display to fail when there is no ExAC data included in the MyGene.info response (https://github.com/ClinGen/clincoded/issues/883#issuecomment-240560839).
2) Minor text change in data source attribution (https://github.com/ClinGen/clincoded/issues/800#issuecomment-240558170).
1. Login and use **CA501097** CAR ID to select variant.
2. Click through all the tabs and back to the Gene-centric tab. Expect to see …
=> Connects to #903. Connects to #904.

src/clincoded/static/components/variant_central/interpretation/shared/calculator.js, src/clincoded/static/components/variant_central/interpretation/shared/form.js
This PR is for ticket #910 to edit Pathogenicity calculator.
**Changes**
1. Edited code in file `src/clincoded/static/components/variant_central/interpretation/shared/calculator.js` to handle case of multiple PVS and case of multiple Stand alone.
2. Edited code in file `src/clincoded/static/components/variant_central/interpretation/shared/form.js` to assign option "very strong" to criteria PS2 only.
**Test**
* In VCI, enter a variant id, click Save and View Evidence, click Start New Interpretation.
* In Population tab or Predictors tab, click any "P" criteria, expect not to see "PXX_VS" option in pulldown list, like below.
* In Population tab select Met at BA1 and Save. And then, in Predictors/Missense tab select "BP4_stand alone" at BP4 and Save. Expect to see:
* Select "Not Evaluate" at …
=> Connects to #910 new rules and very-strong in PS2 only

src/clincoded/static/components/variant_central/interpretation/mapping/evidence_code.json
Update BA1 hover text in criteria bar from:
- "MAF is too high for disorder"
To:
- "Allele frequency greater than 5% in a population database"
As in:
=> Connects to #916. Fix BA1 hover text

src/clincoded/static/components/variant_central/interpretation/mapping/evidence_code.json
PP3 and BP4:
BP3: 
PP4:
PP5:
Testing:
1. Get to VCI and begin interpretation
2. Confirm that definition text for the above criteria codes have no typos
=> Connects to #928. Connects to #936. Fix typos in criteria definitions.

src/clincoded/static/components/variant_central/interpretation/basic_info.js
Some ClinVar variants may have no NC genomic information nor the NM transcripts (e.g. neucleotide change), such as http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=91723. When the ClinVar variant has no NM transcript, it stalls other scripts because currently the VCI assumes the presence of at least one NM transcript in a ClinVar variant. As such, changes are added to work around this issue so that other scripts are still executed.
1. Login and use variant_id **91723** as the variation selection interface.
2. Proceed to the Basic Info tab and expect to see the "_No ClinVar Primary Transcript was found for ClinVar VariationID 91723."_ message being displayed in the **ClinVar Primary Transcript** table. Also …
=> Connects to #946. ClinVar variant no genomic info.

src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/libs/parse-resources.js
1. This PR primarily addresses the issue in which a ClinVar variant does not return the `<ProteinChange>` node in its XML data but has legit protein change (e.g. http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=17662). As such, we need to show the correct message in the "Other Variants in Same Codon" panel.
2. Certain dbnsfp object in the myvariant.info data return `phylo.p100way` and `phastcons.100way` fields (e.g. http://myvariant.info/v1/variant/chr14:g.23884860C%3ET) instead of `phylo.p7way` and `phastcons.7way` fields (e.g. http://myvariant.info/v1/variant/chr3:g.71019907G%3EA). I understand that myvariant.info is in the process of changing `p7way` to `p100way` for the predictors. Until they are finished, we need to …
=> Connects to #935. Codon search changes.

src/clincoded/static/components/variant_central/actions.js
Testing:
1. Get to VCI
2. Attempt to associate disease that is not in db
3. Confirm that the Submit button is re-enabled after throwing the Orpha ID not found error
=> Connects to #945. Associate Disease modal submit button spinner bugfix

src/clincoded/static/components/activity_indicator.js, src/clincoded/static/components/variant_central/helpers/clinvar_interpretations.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/scss/clincoded/modules/_activity_indicator.scss, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/static/scss/fontawesome/_icons.scss, src/clincoded/static/scss/style.scss
1. Added a stateless activity indicator method that can be re-used, along with its own CSS module.
2. The downside of this activity indicator implementation is that it requires the parent DOM element (new or existing) to have `position: relative;` CSS property.
3. The activity indicator has been applied to the tables that are dependent on fetched data for the Basic Info, Population, Predictors, and Gene-centric tabs.
1. Login and use **17662** and/or **21134** variant_id at the variation selection interface.
2. Upon being redirected to the Basic Info tab, expect to see the display of the activity indicators in each table until the data starts being rendered. Particularly for the ClinVar Interpretations table, the "No data was found..." message …
=> Connects to #925. Adding activity indicator.

src/clincoded/static/components/variant_central/record_curator.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Testing:
1. Get to VCI
2. Start interpretation
3. Switch accounts and repeat steps 1 and 2
4. Confirm that the text on the 'Other Interpretations' section does not wrap prematurely
Other change:
* Interpretation lists should not have a comma before the '(last edited' text begins
=> Connects to #951. Interpretation history text wrapping

src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/population.js
Please have the Chrome DevTools console open while testing this PR.
1. Login and use **55847** variant_id at the variation selection interface.
2. Proceed to the **Population** tab and expect to see allele frequency data being displayed at the top of the tab as expected.
3. Also expect to see **no** VEP data fetching/request errors originated from the `population.js`.
=> Connects to #921. Consolidate Ensembl VEP fetch methods.

src/clincoded/static/components/variant_central/interpretation/population.js
1. Login and use 55847 variant_id at the variation selection interface.
2. Proceed to the Population tab and expect to see **no** ExAC Constraint Score linkout at the top of population tab.
3. Start a new interpretation and also expect to see **no** ExAC Constraint Score linkout at the top of population tab.
=> Connects to #923. Removed ExAC Constraint Score linkout on population tab.

src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/functional.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/segregation.js, src/clincoded/static/components/variant_central/interpretation/shared/complete_section.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Testing:
1. Get to VCI, begin interpretation
2. Confirm that the 'complete section' checkbox prompts are moved to the bottom, below the data tables and forms, but before the external resource crediting lines
3. Confirm that the text for each prompt is correct for each tab
Testing:
1. Get to VCI, begin interpretation
2. Confirm that the gene-centric tab does not have the complete section checkbox prompt
=> Connects to #963. Connects to #965. Change location and text of section complete checkboxes

src/clincoded/static/components/variant_central/interpretation/mapping/evidence_code.json, src/clincoded/static/components/variant_central/interpretation/shared/form.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
* Disabled disease-dependent logic for rendering and saving data in `form.js`
* Updated form rendering to support HTML codes form json for descriptions
* Fixed typos in descriptions
Testing:
1. Load VCI, begin interpretation
2. Confirm that the correct criteria are marked as 'Disease-specific'
3. Confirm that disease-specific criteria are still available for editing and saving with no disease being associated to interpretation
3. Save interpretation with and without disease-specific tags, with and without disease associated to interpretation, and confirm that things work
Testing:
1. Load VCI and begin interpretation on Windows machine (Chrome, since FF login is broken)
2. Check PP3 (missense subtab) and PVS1 (lof subtab) and confirm that the text in the description box does not ellipsis. …
=> Connects to #947. Connects to #937. Connects to #978. Disease-dependency overhaul. Fix rendering on Windows.

src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
1. The static "Splice Site Predictors" table is duplicated and placed under the "Silent & Intron" sub-tab.
2. Fixed the wrapping issue for the external link icon next to **HumanSplicingFinder** in the static "Splice Site Predictors" table.
1. Login and use **12345** at the variant selection interface.
2. Proceed to the **Predictors** tab. Expect to see that the external link icon next to **HumanSplicingFinder** is no longer wrapped to the next line in the static "Splice Site Predictors" table under the "Missense" sub-tab.
3. Click on the "Silent & Intron" sub-tab. Expect to see the same static "Splice Site Predictors" table and without the wrapping issue for the external link icon next to **HumanSplicingFinder**.
=> Connects to #933. Connects to #922. Splicing table.

src/clincoded/static/components/select_variant.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**This PR modifies UI of variant selection page. Changes are:**
1. Move data selection box to the top of page.
2. Add a new warning note under the box.
**Functionality of variant selection is not changed.**
**Related code changes are in file `src/clincoded/static/components/select_variant.js`. They are:**
1. Relocate `<Input>` element.
2. Add a `<div>` element with bootstrap classes "alert alert-danger" for warning note.
**Test Steps**
* Start VCI, expect to see variant selection page as:
* Select "ClinVar Variant ID" and click `Add Variant ID` button. In `ClinVar Variant` module , enter variant id "12345", click `Retrieve from ClinVar` button and then click `Save and View Evidence` button. Expect to see all  buttons functioning as before.
=> Connects #973 kl snp warning

src/clincoded/schemas/interpretation.json, src/clincoded/schemas/provisional_variant.json, src/clincoded/tests/data/inserts/interpretation.json, src/clincoded/tests/data/inserts/provisional_variant.json
This PR has schema changes for summary page. There is no change at UI or logic involved.
**Code Changes**
1. Add a non-required data property `markAsProvisional` in file `src/clincoded/schemas/interpretation.json`.
2. Remove `enum` from property `autoClassification` and property `autoClassification`in file `src/clincoded/schemas/provisional_variant.json` to allow taking new type of classification.
3. Edit test data files `src/clincoded/tests/data/inserts/interpretation.json` and `src/clincoded/tests/data/inserts/provisional_variant.json` to match the schema changes.
**Test**
* Go to [http://localhost:6543/interpretations/b3e105b5-d08a-4520-9305-c1419d9027d4/](http://localhost:6543/interpretations/b3e105b5-d08a-4520-9305-c1419d9027d4/) and expect top see `"markAsProvisional": false,` in …
=> Connects to #997 kl edit schema for summary

src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/libs/parse-resources.js
This PR primarily implements the UIs to display the "Data is currently only returned for single nucleotide variants" message in the tables on the "Population" and "Predictors" tabs (rather than trying to display data), when the user-selected variant is not a single nucleotide variant.
**Please use the following IDs while testing different use cases:**
duplication - Variant ID 17677
deletion - Variant ID 55555
deletion/insertion - Variant ID 179355
insertion - Variant ID 37401
inversion - Variant ID 242209
haplotypes - Variant IDs 7901 and 14180
1. Login and use one of the IDs given above at the variation selection interface.
2. Proceed to the **"Population"** tab and expect to see the _"Data is currently only returned for single nucleotide …
=> Connects to #927. Indel and haplotype variants.

src/clincoded/static/components/variant_central/helpers/clinvar_interpretations.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Adding method to parse the following selected ClinVar interpretation summary data:
- Review Status
- Clinical significance
- Last evaluated
- Number of submission(s)
As discussed with the curators, the conditions are not needed at the top of the table as they are already displayed individually for their respective RCVs in the table.
Example ClinVar variation:
http://www.ncbi.nlm.nih.gov/clinvar/variation/55847/
1. Login and use 55847 at the variation selection interface.
2. On the Basic Info tab, expect to see the following interpretation data being displayed at the top of the ClinVar Interpretations table:
- Review Status
- Clinical significance
- Last evaluated
- Number of submission(s)
=> Connects to #942. ClinVar interpretation summary.

src/clincoded/schemas/curatorHistory.json, src/clincoded/schemas/external_evidence.json, src/clincoded/schemas/extra_evidence.json, src/clincoded/schemas/interpretation.json, src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/functional.js, src/clincoded/static/components/variant_central/interpretation/segregation.js, src/clincoded/static/components/variant_central/interpretation/shared/extra_evidence.js, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/types/__init__.py
* Added in ability to add PMID evidence to an `interpretation` object via the new `extra_evidence` object
* Added in a module to display this evidence list in the VCI (multiple times per page if needed)
* Module also supports in-table modal popup to add the articles (via the `add_external_resource` modal) and in-table editing and deleting of `extra_evidence` objects
* The `interpretation` object links to `extra_evidence` via the `extra_evidence_list array`
* The `extra_evidence` object currently only links to `articles`, but can theoretically support different objects such as `families`, `groups`, etc., as well.
**Note:** the article link from `extra_evidence` is currently an array to support multiple articles per evidence object, but the UI only allows for one article per evidence …
=> Connects to #954. Ability to associate PMID in VCI

src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/helpers/clinvar_interpretations.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/shared/externalLinks.js, src/clincoded/static/components/variant_central/record_gene_disease.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**This PR has changes for parsing and displaying ClinVar interpretation data in Basic Info tab, including:**
1. Only retrieve and display "primary" RCVs.
2. Retrieve and display not only "Disease" type but also all other types of condition associated to a RCV.
3. Add external links to HPO and MeSH. In case source name of an identifier is not "MedGen", "Orphanet", "OMIM", "HPO" or "MeSH", display identifier as "source name: id" without link since pre-set urls to external web pages are limited to the 5 sources above currently.
**Test Steps**
* Test 1 (primary RCVs)
- In VCI, use ClinVar variant "15333" and expect to see only 4 primary RCVs (RCV000016575, RCV000016573, RCV000016574 and RCV000224000) as:
Related meta data in ClinVar xml file: 
xml file at: …
=> Connects to #915 kl bug brackets no disease

src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
This PR fixes a bug causing error and stop AWS instance. 
The bug is resulted by a CSS pseudo class `:not(:first-child)` in file `/src/clincoded/static/scss/clincoded/modules/_curator.scss` line 1182-1183.
It has been corrected by removing the pseudo class  from  the file.
**Test**
* Login to instance [https://bug-css-aws-6457060-kangliu.demo.clinicalgenome.org](https://bug-css-aws-6457060-kangliu.demo.clinicalgenome.org)
* In VCI, use ClinVar variant 13969 and expect to see Basic Info tab in Evidence View as:
=> Connects to #1013 kl bug css aws

src/clincoded/static/components/curator.js, src/clincoded/static/components/variant_central/actions.js, src/clincoded/static/components/variant_central/header.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/mapping/evidence_code.json, src/clincoded/static/components/variant_central/interpretation/shared/calculator.js, src/clincoded/static/components/variant_central/interpretation/summary.js, src/clincoded/static/components/variant_central/title.js, src/clincoded/static/scss/clincoded/_variables.scss, src/clincoded/static/scss/clincoded/modules/_curator.scss
1. While on the Summary page, clicking on the browser's **Back** button instead of the "Return to Interpretation" button will cause the page to lose its interpretation state (e.g. such as taking the user back to the "Evidence Only" view).
1. The provisional form on the summary page can be saved even when the modified pathogenicity and its reason fields have `null` values.
2. In the use case above, we are at least storing a string value in the `provisional-variant` object for the calculated pathogenicity and a boolean value in the `interpretation` object for the provisional interpretation checkbox.
3. The displayed **Calculated Pathogenicity** uses the in-app state as its primary data source and the stored value as its secondary data source. The …
=> Connects to #943. VCI summary page.

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation/shared/credit.js, src/clincoded/static/components/variant_central/record_variant.js
1. Removed instances of `this.props.protocol +` and `this.props.href_url.protocol +` associated with NCBI API and external http requests.
2. Changed all instance of `http` to `https` associated with NCBI in `global.js`.
3. Prepend `https` to URL mappings associated with NCBI in `global.js`.
1. Open Chrome Dev Tools console.
2. Login and use 15333 variant_id at the variation selection interface. Expect to see a list of HGVS terms being returned in the modal. Also expect to see no XHR error for the _Eutils_ API call in the console.
3. Click the **Save and View Evidence** button and proceed to the **Basic Info** tab. Expect to see data being displayed in the **ClinVar Interpretation and Supporting Records** and **ClinVar Primary Transcript** tables. …
=> Connects to #1022. Update NCBI API and external http requests to https.

src/clincoded/static/components/app.js, src/clincoded/static/components/home.js, src/clincoded/static/components/select_variant.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/static/scss/fontawesome/_icons.scss
1. In the process of addressing #1004, I noticed that the **phastCons100way** score being displayed as "--" rather than "0". So I added a method to convert individual number scores to strings so that 0s are not interpreted as `null`.
1. On the landing page, expect to see the `help` icon button at the top nav next to the **Login** button without logging in.
2. On the landing page, also expect to see the new content/layout. Click on various links and expect to be taken to the intended pages.
3. Login and proceed to the variation selection page. Expect to see the updated note with "...the instructions below..." rather then "...above instructions..." right below the selection dropdown.
4. Use 54321 variant_id and proceed to the **Predictors** tab. In …
=> Connects to #1024. Connects to #1004. Connects to #1008.

src/clincoded/static/components/variant_central/interpretation/summary.js
A bug was discovered for the MoI term display on summary page. When a non-HPO MoI term was selected, the display was blank for the MoI term on the summary page.
1. Login and use 15333 variant_id.
2. Start a new interpretation and add a non-HPO mode of inheritance (e.g. "codominant" or "other"). Proceed to the summary page and expect to see it being displayed next to the MoI term.
3. Return to interpretation and change to a HPO mode of inheritance (e.g. with HP:XXXXXX). Proceed to the summary page and expect to see it being displayed as a link next to the MoI term.
4. Return to interpretation and remove the MoI. Proceed to the summary page and expect to see "None" being displayed next to the MoI term.
=> Connects to #1028. Non-HPO MoI term display on summary page

src/clincoded/static/components/variant_central/interpretation/shared/extra_evidence.js, src/clincoded/static/components/variant_curation.js
Variant added history item now links to VCI evidence view.
Testing:
1. Add variant via VCI. Confirm that dashboard entry for variant add links to VCI properly.
2. Add variant via GCI (family, individual, experimental). Confirm that dashboard entry for variant add links to VCI properly.
Non-admin users can delete extra evidence in VCI now.
Testing:
1. Login as non-admin account
2. Get to VCI, begin interpretation, then add PMIDs as extra evidence
3. Confirm that deleting these evidence items work
=> Patch for #905 and #954/#1030

src/clincoded/static/components/variant_central/actions.js, src/clincoded/static/components/variant_central/index.js
Added conditional checks on the current modified and calculated pathogenicity upon deleting the associated disease. If either the following conditions are met, the updated code sets the `markAsProvisional` field to `false` during form submission:
1. modified pathogenicity === "Likely pathogenic" || "Pathogenic".
2. If modified pathogenicity value is `null`, but calculated pathogenicity === "Likely pathogenic" || "Pathogenic".
1. Login and use 15333 variant_id.
2. Start a new interpretation. Evaluate various criteria so that the calculated pathogenicity is either "Likely pathogenic" or "Pathogenic". And add an associated disease.
3. Proceed to the summary page. Check the provisional checkbox and **Save** the form. Notice that the provisional status …
=> Connects to #1032. Deleting disease in modal.

src/clincoded/static/components/select_variant.js
1. Login and proceed to the variation selection interface.
2. Expect to see the **red** note being displayed as the following screenshot.
=> Connects to #1037. Updated SNV variant note text.

src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/libs/parse-resources.js
1. ClinVar IDs that don't have GRCh37 and GRCh38 hgvs terms would cause the display of content on the Gene-centric tab to stall because it is dependent on the returned data from myvariant.info and/or VEP.
2. ClinVar IDs that don't have any gene related metadata would cause the display of ClinVar RCV table to stall because the parser fails to evaluate the condition of missing `GeneList` node in the returned XML data.
1. Login and use 91723 or 208846 variation id.
2. Proceed to the **Basic Info** tab and expect to see data being displayed in the **ClinVar Interpretation and Supporting Records** table.
3. Proceed to the **Gene-centric** tab. Expect to see data being displayed and the activity indicators are no longer stalled.
4. Return to the variation …
=> Connects to #1039. Handle ClinVar variants that have no gene metadata.

src/clincoded/static/scss/clincoded/modules/_curator.scss
Quick patch to adjust landing page bottom 2 panel border box height so that they extend to enclose content within smaller window width.
**Known issue:**
Due to time constraint, the boxes of 2 bottom panels are not in equal height when in smaller window width. Will address it in the next release.
1. Go to landing page and try various smaller window width.
2. Expect to see the border boxes of bottom 2 panels to extend to enclose their content.
=> Connects to #1043. Landing page CSS fix.

src/clincoded/static/components/variant_central/interpretation/gene_specific.js
Added condition to prevent Gene-centric tab to stall when uniprot data is absence in mygene.info response.
1. Login and use 10505 variant_id.
2. Proceed to the **Basic Info** tab and then click through other tabs all the way to the **Gene-centric** tab.
3. Expect to see individual tabs dispalying their own content and none of them is stalled or hung.
=> Connects to #1046. Gene-centric tab stalls on missing uniprot data.

src/clincoded/static/components/variant_central/interpretation/summary.js
In **R7**, `handleProvisionReset()` method and `this.handleProvisionalCheckBox()` method invocation (in the `componentWillReceiveProps` lifecycle method) were added in the **Summary** page component to reset the `markAsProvisional` field in the `interpretation` object when an associated disease is deleted given the modified/calculated pathogenicity being either **Likely pathogenic** or **Pathogenic**.
Given the changes made later in #1036, the method and handling described above are no longer needed.
1. Login and use 15333 variant_id at the variation selection interface.
2. Start a new interpretation. Evaluate various criteria so that the calculated pathogenicity is either "Likely pathogenic" or "Pathogenic". And add an associated disease.
3. …
=> Connects to #1052. Summary page component code update.

src/clincoded/static/libs/parse-resources.js
Added conditional statement in the `parseClinvarExtended()` method in the `parse-resources.js` file to evaluate the existence of HGVS metadata in the returned ClinVar variant response. Currently, such ClinVar variants would cause the the fetching process to fail and thus stall other scripts to execute.
1. Login and use 242361 or 243041 at the variation selection interface.
2. Proceed to the **Basic Info** tab. Expect to see RCV data being displayed in the **ClinVar Interpretation and Supporting Records** table.
=> Connects to #1054. ClinVar variant missing HGVS metadata

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**Steps to test -- landing page:**
1. Go to landing page and try various browser window widths.
2. Expect to see the 2 bottom panels' border boxes are in equal height until the 2 panels stack within the mobile viewport width.
**Steps to test -- variation selection modal:**
1. Login and use 55602 variant_id to retrieve variant metadata for the display in the modal.
2. Try various browser window widths and expect to see the display of variant metadata in the selection modal to be consistently having the labels on the left and the metadata on the right. And no text would be clipped within the mobile viewport width.
=> Connects to #1049. CSS styling fixes.

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/variant_central/interpretation/population.js
**Steps to test -- variation selection modal:**
1. Login and use **CA003323** CAR id to retrieve variant metadata for the display in the modal.
2. Try various browser window widths and expect to see the display of variant metadata in the selection modal to be consistently having the labels on the left and the metadata on the right. And no text would be clipped within the mobile viewport width.
**Steps to test -- VEP attribution icon:**
1. Login and use **37644** for selecting the variant.
2. Proceed to the **Population** tab and expect to see the **Ve!P** icon replacing the **VEP** label in the header of the **1000 Genomes** table, even when there is population data displayed in the table.
=> Connects to #1073. VCI UI bugs.

src/clincoded/static/components/add_external_resource.js
This PR fixes a bug that CA id must have 6 digits only, ticket #1098. It's fixed by editing a pattern (line 670) in function `carValidateForm` in file `/src/clincoded/static/components/add_external_resource.js`.
**Test**
* Start VCI
* Select `ClinGen Allele Registry ID (CAID)'`, enter "CA10575430" and expect to see
=> Connects to #1098 kl bug caid

src/clincoded/schemas/family.json, src/clincoded/tests/data/inserts/family.json
This PR added data properties in schema file `src/clincoded/schemas/family.json` and edited test data in file `src/clincoded/tests/data/inserts/family.json` for family/gegregation rework. New data properties are:
- numberOfAffectedWithGenotype
- numberOfUnaffectedWithoutBiallelicGenotype
- numberOfSegregationsForThisFamily
- inconsistentSegregationAmongstTestedIndividuals
- explanationForInconsistent
- familyConsanguineous
- pedigreeLocation
- lodPublished
- publishedLodScore
- estimatedLodScore
- includeLodScoreInAggregateCalculation
- recessiveZygosity
**Test**
* Go to [http://localhost:6543/families/a20e9182-18fa-11e5-96d1-60f81dc5b05a/?format=json](http://localhost:6543/families/a20e9182-18fa-11e5-96d1-60f81dc5b05a/?format=json) and expect to see new data properties above in …
=> Connects to #1096 kl schema familysegregation rework

src/clincoded/static/components/mixins.js, src/clincoded/tests/data/inserts/user.json, src/clincoded/tests/features/browsersteps.py, src/clincoded/tests/features/select_variant.feature, src/clincoded/tests/features/test_generics.py
Adds some BDD tests for the select-variant page, and changed the demo login.
To run tests:
`bin/test -m bdd -v -v`
(all bdd tests should run normally...checks the ClinVar and CAR API on the select-variant page)
To test login, click on the "Demo Login" from nav bar.
(logs in as usual)
=> Connects to #1076 kd selenium

src/clincoded/static/components/curator.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/select_variant.js
1. Fixed a bug in which removing a variant of 2 from the family page does not trigger an update on the associated Proband's variant count (same for adding a variant on the family page).
2. Fixed a bug in which changing "Hemizygous" (or "Homozygous") to "No Selection" for zygosity does not trigger an update in the Proband's current zygosity field.
**Known issue:**
1. On the family view page, in the **Family - Variant(s) Segregating with Proband** panel, we seemingly only show variants associated with a Proband. If no Proband in the family, the declared `variants` variable defaults to `[{}]` which always has count of 1, regardless of the absence of object keys. As a result, the rendering would still display the header (which can also be seen in curation-test instance). …
=> Connects to #1093. GCI family and individual pages.

src/clincoded/static/components/app.js, src/clincoded/static/components/home.js
The code that sets the `demoWarning` state in the `home.js` (`Home` component) is a duplicate of `getInitialState` code block in the `app.js` (app level). Furthermore, the `demoWarning` state has already been set at the app level.
So, in this rework, the implementation is to pass the `demoWarning` state from the app level to the child `Home` component level so that the duplicate code can be removed.
Steps to test:
1) Add the following entries in the `/etc/hosts` file:
```
127.0.0.1    curation.clinicalgenome.org
127.0.0.1    curation-test.clinicalgenome.org
127.0.0.1    production.clinicalgenome.org
```
2) Go to **curation-test.clinicalgenome.org:6543** and expect to see the dark blue message in the light blue panel.
3) Go to **curation.clinicalgenome.org:6543** and …
=> Connects to #1132. Rework of landing page demo note implementation.

src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/functional.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/segregation.js, src/clincoded/static/components/variant_central/interpretation/shared/extra_evidence.js, src/clincoded/types/__init__.py
Adds a new class to the extra evidence module that displays a view-only view-all mode for extra evidence, to be used on Evidence View mode only. Also adds extra evidence tables to many more sections of the VCI.
Testing:
1. Enter VCI, enter interpretation mode
2. Enter extra evidence in a number of places
3. Enter VCI for same variant as another user
4. In Evidence View mode, confirm that the extra evidence added as the previous owner is visible
5. Enter interpretation mode, and add extra evidence in a number of overlapping and non-overlapping places
6. Go back to Evidence View mode, and confirm that the extra evidence tables have updated properly with the new entries
=> Connects to #1145. Connects to #1109. Expand extra evidence functionality

src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js
The Proband scoring option/data should be only available to:
1. A Proband individual who is associated with a family.
2. An individual who is a Proband but not associated with a family.
1. Login and add a new PMID from a new or pre-existing GDM.
2. Add a new family. Saving the form by filling out only the **required** fields, but PLEASE add at least 1 variant and associate it with a Proband individual.
3. On the intermediate page upon saving the family form page, proceed to adding a Non-Proband individual to the family.
4. On the Non-Proband individual form page, expect to see **NO** individual score panel being displayed at the bottom of the page.
5. Save the form page and return to the Curation-Central page. Click on the "Edit" link below the …
=> Connects to #1135. No scoring option available to non-proband individuals.

src/clincoded/static/components/variant_central/interpretation/shared/form.js
PS4 crosscheck error now references the correct criteria code:
Testing:
1. Get to VCI and begin interpretation
2. Evaluate 'Met' on PM2 in Population subtab
3. Evaluate 'Met' on PS4 in Segregation/Case subtab, and confirm that the error message references the correct criteria codes
=> Connects to #1151. PS4 error message bugfix

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js
* Implemented ability to associate CAR Variants in the GCI's family, individual, and experimental pages (#957)
* `submitForm` methods no longer ping the internal database to get a variant's UUID. The Add External Resource modal response handles this now
* CAR IDs are displayed now whenever applicable with appropriate labels
* Added Clear option to GCI regarding variants (#1136)
* Added flag to control rendering of the Edit button for the Add External Resource modal module
* Removed old code and revised remaining code in the GCI's family, individual, and experimental pages regarding:
* ClinVar-specific variant data
* Free text
* Revised logic regarding adding of proband individual and variants via Family page
* Added link to edit proband individual from Family page (edit mode)
Testing:
1. …
=> Connects to #957. Connects to #1136. Add CAR and Variant Clear support to GCI

src/clincoded/schemas/gdm.json, src/clincoded/schemas/interpretation.json, src/clincoded/static/components/create_gene_disease.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/mapping/modes_of_inheritance.json, src/clincoded/static/components/variant_central/actions.js, src/clincoded/static/components/variant_central/interpretation/summary.js, src/clincoded/static/components/variant_central/title.js, src/clincoded/tests/features/create_gene_disease.feature
1. This PR is primarily for the changes made to the mode of inheritance, in which adjectives are added to the following core MOIs: `Autosomal dominant inheritance (HP:0000006)`, `Autosomal recessive inheritance (HP:0000007)`, `Mitochondrial inheritance (HP:0001427)`, `X-linked inheritance (HP:0001417)` and `Other`.
2. The changes made to the mode of inheritance also include moving the following core MOIs to be adjectives under the `Other` core MOI: `Y-linked inheritance (HP:0001450)`, `Somatic mutation (HP:0001428)` and `Multifactorial inheritance (HP:0001426)`.
3. The mode of inheritance changes will affect the GDM creation in GCI as well as the MOI association with interpretation in VCI.
4. Curators are not required to select an adjective for any given core MOIs …
=> Connects to #1104. Adding adjectives to mode of inheritance.

src/clincoded/schemas/gdm.json, src/clincoded/schemas/group.json, src/clincoded/schemas/interpretation.json, src/clincoded/static/components/dashboard.js, src/clincoded/static/components/gdm.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/tests/features/generics.feature
Adds master interpretation list, much like the master GDM list. Adds link to the master interpretation list to Dashboard. Minor changes to master GDM list for consistency in sorting and display. Changes to JSON schema files is to add additional return fields, not actual schema changes. 'Last Edit' column value is only available/dependent on Evaluations in Interpretation.
Testing:
1. Go to Dashboard
2. Click on 'View all interpretations' link
3. Confirm that columns sort properly and that the filtering works fine
4. Confirm that clicking on interpretation row takes you to that variant in VCI
=> Connects to #1150. Interpretation list

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/home.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/select_variant.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/record_gene_disease.js, src/clincoded/static/scss/clincoded/_base.scss
Implements CSS rules so that external links automatically have the external-link font awesome icon attached to it. Removes previous manually added instances of the external-link icon from the code.
Links that do not include the external-link icons include ones pointing to `localhost` and `instance/demo/production/curation-test/curation.clinicalgenome.org`.
Testing:
1. Rebuild CSS
2. Use site and check to see if external-link icons exist where they should
=> Connects to #1159. Implement linkout css

src/clincoded/static/components/curation_central.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Proper display of CAR variants in the following locations of the GCI:
* Gene-Disease-Record variants header
* Curation palette
* Curate variant page
* View pages for Family, Individual, and Experimental items w/ variant data
Also includes separate bugfix where old GDMs with no `modeInheritanceAdjective` variable would not load.
Testing:
1. Get to GCI
2. Add CAR variants (CA003323 - both ClinVar and CAR info, CA501068 - only CAR info) to Family, Individual, and Experimental curation pages
3. Confirm that the Variants properly display data in the above listed locations
=> Connects to #1155. Expand CAR support in GCI

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
Reworked the family and individual curation pages of the VCI to support the new zygosity workflow. Users are now asked to check a checkbox depending on zygosity, and are always given 2 variants to add regardless of their zygosity selection. Variants are never required, also regardless of their zygosity selection.
Usage of variables in family and individual curation pages were changed to support this change. The handlers for the zygosity checkboxes were done so that the old data scheme can be used.
Testing:
1. Get to GCI
2. Do family and individual curation with zero, one, or two variants, and different selections of the zygosity checkboxes. Confirm that the variants display properly in the View and Edit pages.
3. Edit the variants and zygosities. Confirm again that the variants display …
=> Connects to #1141. Reworked zygosity workflow

src/clincoded/static/components/individual_curation.js
For a non-proband individuals (associated with a family or not), we do not need to ask them the questions about trans and de novo.
1. Login and create a new GDM.
2. Given the newly created GDM, create a new Family evidence and add a proband individual to the family with one or more variants. Now go into the Individual page and expect to see the 3 questions (trans, de novo, maternity) being shown.
3. Save this Family evidence with proband associated. Now add a non-proband individual to this family with one or more variants. Now go into the Individual page and expect to see the 3 questions (trans, de novo, maternity) NOT being shown.
4. Now create a new Individual evidence and set it to be a proband. Then add a variant and expect to see the 3 …
=> Connects to #1124. Remove trans and de novo questions for non-proband individuals.

src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js
Downstream fix for issues caused by #1141.
Adds in the ability for the user to create proband individuals via the family curation page even if they have no variant data input. In #1141 the user could 'Submit' the form and it would save fine, but an Individual would not be created due to lack of variants, causing issues in the submit page, as well as acting as unexpected behavior. The changes here remove and/or replace checks for variants during individual creation.
Testing:
1. Get to the GCI's Family Curation page
2. Create Family w/ Proband Individual with no Variants (Add Individual name and orphanet; zygosity is optional)
3. Confirm that the Proband Individual is created properly
4. Add Variants for just-created family and confirm that they are saved properly to both Family and …
=> Connects to #1167. Support ability to create proband individual w/ no variant

src/clincoded/static/components/family_curation.js
Bunch of fixes to the LOD-related dropdown logic in the Family Curation page of the GCI.
After discussing with @selinad it was decided that the 'For Recessive Only' field will NOT be locked when in a GDM that is not Autosomal Recessive to retain flexibility for users.
I've confirmed that changing the 'For Recessive Only' field for an Autosomal Dominant GDM does NOT affect the calculated LOD score, and that changing the '# Segregation' field for an Autosomal Recessive GDM does NOT affect the calculated LOD score, both in code and UI.
Testing:
1. Enter GDM w/ Autosomal Dominant MOI, Family Curation. Test many permutations of interaction to ensure that the LOD Score and Include LOD Score in Final Calculation fields reset properly. Examples:
- Enter Published LOD Score and select Include LOD …
=> Connects to #1177. LOD dropdown/value fixes

src/clincoded/static/components/variant_central/interpretation/summary.js
Merging in existing fix to address the display of "Cannot read property 'resetSelectedOption' of undefined" on the select-variant page when moving from one variant evaluation to a new variant.
To test:
1. Click on "New Variant Curation"
2. Enter a new variant, and save it
3. Start Interpretation: "Interpretation +" on Evidence Only page
4. **Without evaluating any criteria** click "View Summary" 
5. Click "New Variant Curation" 
Normal "Search and Select Variant" page should be seen
=> Connects to #1129 bug new variant curation button

src/clincoded/static/components/curator.js
An extra warning message `Deleting this individual will remove the association between its variants and the Family with which the Individual is associated.` has been added to the individual deletion modal for the to-be-deleted item if he/she has both associated variant(s) and associated family.
1. In GCI, add a family evidence and add 2 individuals to this family -- one with associated variant(s) and one without.
2. On the "Edit" form of the individual _with_ associated variant(s), click on the `Delete` button and expect to see the extra warning message appearing in the modal.
3. On the "Edit" form of the individual _without_ associated variant(s), click on the `Delete` button and expect to see NO extra warning message appearing in the modal.
=> Connects to #1123. Warning message in deletion modal.

src/clincoded/schemas/provisionalClassification.json, src/clincoded/upgrade/provisionalClassification.py
An upgrade script has been created to add the new properties to existing provisionalClassification objects in the database.
1. Log into instance https://1196-jz-provision-schema-d451a32-jzhen.demo.clinicalgenome.org and go to ^/provisional/.
2. Reveal any one of the existing provisional records and expect to see the following properties being added to the objects with their default values: `replicatedOverTime` and `contradictingEvidence`.
=> Connects to #1196. Schema changes to provisionalClassification object.

src/clincoded/static/libs/bootstrap/navigation.js
1. Click on the **"Help"** navbar button at top.
2. Then click on the **"Contact Helpdesk"** and expect to see the user's default mail client being launched with **"clingen-helpdesk@lists.stanford.edu"** in the **"To:"** field.
=> Connects to #1198. Add helpdesk link.

src/clincoded/static/components/individual_curation.js
Fixes bug where if a proband individual connected to a family had a score connected to it, any edits to the family would fail. This was caused by a combination of 1) an improper comparison between the zygosity value of the form and the zygosity of the individual leading to an unnecessary update of the individual object and 2) no flattening of the `scores` array of the individual, causing a `422` error upon a `PUT` attempt. Both issues have been corrected in this PR.
Testing:
1. Create Family w/ Proband Individual and 1 Variant.
2. Score the Individual
3. Go back to the Family and edit any non-individual field, and confirm that the object saves.
4. Go back to the Family and add a Variant to the Individual, but do not change anything else. Confirm that the object saves (this is to confirm …
=> Connects to #1199. Family proband save bugfix

src/clincoded/static/components/variant_central/interpretation/shared/form.js
This PR comments out the bit of code that prohibits the user from assessing on both PM2 and PS4 as 'Met' and above.
Testing:
1. Enter interpretation mode in VCI
2. Assess 'Met' or above on PM2 under Population tab
3. Assess 'Met' or above on PS4 under Case/Segregation tab, and confirm that you are able to do this.
=> Connects to #1195. Remove check for PM2 vs PS4

src/clincoded/static/components/family_curation.js
1. Create/Edit a Family evidence in GCI.
2. On the Family form page, expect to see the label text change (as seen in the screen capture below) for the first 3 questions in the **Family-Segregation** panel.
=> Connects to #1200. Label text change for the Family-Segregation.

src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/score/constants/score_maps.js, src/clincoded/static/components/score/experimental_score.js, src/clincoded/static/components/score/individual_score.js
Changes made for #1206 can not be verified in the GCI interface until they are merged with the PR for #1184.
**Changes made for #1206:**
1. The "Total Score:" text label for the GCI provision summary in the header has been changed to "Calculated Score (Classification):".
2. The "Provisional Classification:" text label for the GCI provision summary in the header has been changed to "Modified Provisional Classification:".
3. The displayed value for "Modified Provisional Classification:" will show "None" (instead of "No Selection") if the curator did not select an option in the modified classification dropdown menu.
**Steps to test #1207:**
1. Create a new GDM and add an Experimental evidence.
2. By selecting different evidence types, expect to see the different default …
=> Connects to #1206. Connects to #1207. Connects to #1209.

src/clincoded/static/components/curator.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
The change made is to set the `publishedLodScore` state outside of the `if (stateObj.lodLocked)` eval in the `loadData` method, as the 'lodLocked' state value appears to be relevant to the `estimatedLodScore` text field.
1. Create a new GDM and add a Family evidence.
2. In the **Family-Segregation** panel, select **Yes** from the **Published LOD score?** dropdown.
3. Enter a decimal number (e.g. 1.5) in the **Published Calculated LOD score** text input field.
4. Select either **Yes** or **No** from the **Include LOD score in final aggregate calculation?** dropdown.
5. Fill out other **required** fields and save the form page.
6. Return to the Family evidence form page and expect to see the **Include LOD score in final aggregate calculation?** …
=> Connects to #1208. Connects to #1190. Fixed disabled Family-Segregation selection dropdown and Generate Summary button.

.travis.yml, versions.cfg
This is related to #551 (which will cover a more robust change to 1.7->2.*->5.*). Elasticsearch was already version bumped to 1.7. on cloud configs, but these are also necessary.
- Update travis `.travis.yml` config
- Update `versions.cfg`file
To test:
-  Go to a travis test. e.g. https://travis-ci.org/ClinGen/clincoded/jobs/192687595
- Locally, run `bin/buildout -c buildout-dev.cfg;`
-  the `bin/commands` folder files should show elasticsearch-1.7.0 in the path for elasticsearch
- All tests should pass
https://kd-elasticsearch-1-7-1d9fb54-karen.demo.clinicalgenome.org/dashboard/
=> Patch: bump elasticsearch version to 1.7

src/clincoded/static/components/family_curation.js
1. Create a new GDM and add a Family evidence.
2. Fill out the **required** fields on the form page.
3. Specifically in the **Family-Segregation** panel, select **Yes** from the `Published LOD score?` dropdown.
4. Enter a "1.2" score in the `Published Calculated LOD score` text input.
5. Select **Yes** from the `Include LOD score in final aggregate calculation?` dropdown.
6. After saving the form page, return to it and edit the LOD score specifically.
7. Select **No** or **No Selection** from `Published LOD score?` dropdown, and then select **Yes** again. Expect to see the `Include LOD score in final aggregate calculation?` dropdown being enabled and the previously saved score being shown.
=> Connects to #1217. Fixed LOD score bug.

src/clincoded/static/components/family_curation.js
* Remove `minVal` limit on # Unaffected individuals fields on Family curation page.
Testing:
1. Get to GCI and navigate to Family curation page
2. Attempt to add a Family w/ # of Unaffected individuals being `1`
3. Ensure that the Family can be saved
* Make it so that GDMs with MOI of X-Linked inheritance uses the same automatic LOD formula as Autosomal Dominant inheritance
Testing:
1. Get to GCI w/ GDM with X-Linked inheritance MOI and navigate to Family curation page
2. Add `14` to `Number of segregations reported for this Family` field
3. Select `No` for `Published LOD score` field
4. Ensure that the `Estimated LOD score` field value is `4.21`
5. Change the `14` to `15` and ensure that the `Estimated LOD score` updates to `4.52`
6. Set to Include LOD score in Calculations and save the …
=> Connects to #1221. Connects to #1227. LOD related changes

src/clincoded/static/components/create_gene_disease.js, src/clincoded/static/components/variant_central/actions.js
**Steps to test #1223:**
1. In GCI, go to the "Create Gene-Disease Record" interface.
2. Expect to see the warning note beneath the dropdown menus.
**Steps to test #1224:**
1. In GCI, go to the "Create Gene-Disease Record" interface.
2. Select any MOI that return a list of adjectives in the dropdown menu beneath it (e.g. AD, AR, X-Linked).
3. In the adjective dropdown menu, select any available adjective and expect to be able to subsequently select the "Select" option which returns the "none" value _without_ switching to a different MOI to reset adjective dropdown menu option.
4. This minor change also applies to the MOI association modal in VCI.
=> Connects to #1223. Connects to #1224.

src/clincoded/static/components/individual_curation.js
This fixes an issue where, if a user scores a Proband connected to a Family, and then removes the variants from the Family (connected to, and required to score a Proband), the Proband's Score still exists by:
1. If the Family's Variant count is 0, it deletes the `evidenceScore` key from the associated Proband Individual, removing all Scores on that Proband Individual
2. Looping through and setting the Proband Individuals' Scores to have a `status` of `deleted` so we do not have orphan'ed `evidenceScore` objects in the database
Testing:
1. Get to GCI and create Family w/ 2 variants + Proband
2. Score Proband
3. Get another person/account to score Proband
4. Remove 1 variant from Family and save. Confirm that the 2 scores are still there
5. Remove last variant from Family and save. Confirm …
=> Connects to #1228. Family-Proband Variants-Scores connection

src/clincoded/static/components/case_control_curation.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/score/viewer.js
1. Log into GCI as primary user and create a new GDM.
2. Add new evidence for Proband Individual, Case-Control, and Experimental. Score each of the evidence.
3. Log out and log in as a different user and **View/Score** each of the evidence in question in the GDM.
4. In each evidence, expect to see:
* Prior to scoring, the evidence's curator score is shown in the **"Other Curator Scores"** panel.
* There is a header in the **"Other Curator Scores"** panel.
* There is a "Curator: " prefix to the curator name in the **"Other Curator Scores"** panel.
=> Connects to #1239. Adding score panel header to evidence viewers.

src/clincoded/static/components/case_control_curation.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/individual_curation.js
The changes in this PR revises the `scoreSubmit` methods in the `individual_curation` , `case_control_curation` , and `experimental_curation` pages so they get the freshest possible data for the evidence and use its scores list. Otherwise, a Save call of the Score using a stale version of the data may remove Scores added previously by other users.
Testing:
1. Create Proband individual and score it as User 1
2. Open the View/Score page for the Proband as User 1
3. As User 2, open the View/Score page for the same evidence on a different browser
4. Score the evidence as User 2
5. Without refreshing the page, Score the evidence as User 1 on the same browser window opened in step 2
6. Confirm that both User 1 and 2's Scores are present
7. Repeat steps 1~6 with a Case Control evidence
8. Repeat …
=> Connects to #1245. Orphaned evidenceScores

src/clincoded/schemas/evidenceScore.json
Removed the 'default' value property of the 'scoreStatus' object in the schema.
=> Connects to #1240. scoreStatus `default` property removal.

src/clincoded/static/components/score/experimental_score.js, src/clincoded/static/components/score/individual_score.js
1. Create a new GDM. 
2. Add a Proband Individual evidence and score it.
3. Upon completion, return to the Proband form page or go to its View/Edit page. Change the Score Status to "No Selection" and click on the "Save" button.
4. Return to the Proband form page or go to its View/Edit page, and expect to see the "No Selection" option being selected in the Score Status dropdown in the score panel.
5. Add an Experimental evidence and score it.
6. Upon completion, return to the Experimental form page or go to its View/Edit page. Change the Score Status to "No Selection" and click on the "Save" button.
7. Return to the Experimental form page or go to its View/Edit page, and expect to see the "No Selection" option being selected in the Score Status dropdown in the score …
=> Connects to #1251. Bug in changing scoreStatus to `No Selection`.

src/clincoded/static/components/case_control_submit.js
This change should make the casecontrol submit page render and not display an error if a casecontrol object is created without a score.
Testing:
1. Create a CaseControl object with no score
2. Confirm that the save page renders properly and that there is no error in console
3. Confirm that the 'Edit' button on submit page takes you back to the casecontrol object, and all the info is there
4. Repeat steps 1~3 with a CaseControl object with a score
=> Connects to #1249. CaseControl submit bug

src/clincoded/static/components/provisional_curation.js
Removed check for `scoreStatus` property in caseControl score object since the caseControl score object will only have the `score` property.
1. Create a new GDM.
2. Add a caseControl evidence and score it.
3. Generate summary and expect to see the caseControl scoring data being shown on the summary page.
=> Connects to #1255. Bug in caseControl score in summary.

src/clincoded/static/libs/parse-resources.js, src/clincoded/tests/features/select_variant.feature
This patch is to convert the CAR's json response's dbsnpid value from an int to a str. This will allow CA IDs that have a dbsnpid but no ClinVar variant ID to be saved in our database.
Testing:
1. Attempt to add CA ID CA2738256 to VCI or GCI
2. Make sure it saves
edit: this is probably a temporary workaround... we may want to convert the field to an int in the database, convert pre-existing values to int, and update our parsers to add them as ints
=> Connects to #1258. Convert CA ID dbsnpids to string

src/clincoded/static/components/provisional_curation.js
This fixes a bug where proband individuals might be counted multiple time during final score calculation in the GCI.
Testing:
1. Create proband individual
2. Create proband individual within Family (for test)
3. Create proband individual within Group (for test)
4. Confirm that scoring is correct on provisional page
5. Add a pubmed annotation w/ no evidence
6. Confirm that scoring is still correct
=> Connects to #1262. Fix proband counting bug on provisional page

src/clincoded/static/components/variant_central/interpretation/gene_specific.js
Added `if-else` condition to the rendering of the 'ExAC Constraint Scores' table rows on the 'Gene-Centric' tab based on the presence of the expected gene data provided in the mygene.info API call.
1. Login and proceed to VCI.
2. Select a variant using CA ID `CA323244`.
3. Upon loading the **Basic Info** tab successfully, click on the **Gene-centric** tab.
4. Expect to see the content of the **Gene-centric** tab.
5. Expect to see the **ExAC Constraint Scores** table to only render 2 rows -- **All ExAC** and **Non-psych**.
=> Connects to #1280. Gene-centric tab bug in VCI.

src/clincoded/static/components/case_control_curation.js, src/clincoded/static/components/create_gene_disease.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/variant_central/actions.js, src/clincoded/static/components/variant_central/interpretation/gene_specific.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**Steps to test #966:**
1. Go to VCI and use ClinVar ID `139214` at the variant selection interface.
2. Upon page load, proceed to the **Gene-centric** tab.
3. Expect to see 2 new columns – **syn Z** and **mis Z** – in the **ExAC Constraint Scores** table, as well as their respective descriptions.
**Steps to test #1288:**
1. Create a new GDM in GCI and add an Experimental evidence.
2. On the Experimental curation page, select **Model Systems** or **Rescue** as the Experiment type. Fill out other **required** fields.
3. In the input fields to add HPO IDs (2 for **Model Systems** and 1 for **Rescue**), enter multiple IDs (delimited with comma) and save the form.
4. Expect to see the form to be successfully submitted without errors indicating the limit of 1 HPO ID.
**Steps to test #1290:** …
=> Connects to #966. Connects to #1288. Connects to #1290. Connects to #1291. Connects to #1293.

src/clincoded/schemas/computational.json, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/upgrade/computational.py
Includes upgrade script to fix previous inconsistently-saved computational objects, and frontend code change to cast data to the same types.
Please see #1295 for additional information
Testing:
1. Begin fresh instance
2. Add variant 102905 to VCI. This variant returns a SIFT score of 1 from myVariantInfo, then save an evaluation under the Predictors tab
3. Add variant 102902 to VCI. This variant returns SIFT scores of [0.028, 0.023], which is converted by the UI to the string '0.028, 0.023', then save an evaluation under the Predictors tab
4. Confirm that the computational values for these contain arrays of numbers, instead of strings or integers.
Testing upgrade:
1. Load up instance w/ production data
2. Confirm that previously-saved computational objects have scores saved as array of …
=> Connects to #1295. Computational object scores

src/clincoded/static/components/curator.js, src/clincoded/static/components/provisional_curation.js
Fixed typo:
'No Reported Evidence' option added to dropdown. Text is "No Reported Evidence (score is based on Experimental evidence only)" but saved value is 'No Reported Evidence'.
Testing:
1. Create GDM
2. Create classification, and save as 'No Reported Evidence (score..'. Confirm that saved value is 'No Reported Evidence'
Removes dropdown value for the calculated classification.
Testing:
1. Create GDM
2. Enter create classification. Confirm that all options are available.
3. Add evidence to bring score up to Limited. Confirm that the Limited option is gone from dropdown.
4. Repeat above for Moderate, Strong, and Definitive.
Definitive:
Strong:
Moderate:
Limited:
No automatic classification:
When GDM has no provisional curation set, text now displays 'None' in upper left instead of 'No …
=> Connects to #1266. Connects to #1279. Connects to #1284. Connects to #1285. Changes to provisional curation dropdown

src/clincoded/search.py, src/clincoded/static/components/search.js
Fix needed to prevent excessive server/index load which would return all results to user if gdm or interpretation was in the request. 
Also adds interpretations to facets for easier access of current status.
Note:  The fix is a precaution for a currently unused search route.
Note: A number of changes were added to search.js but those are only lint fixes, the only section that changed was the `types` object definition near the top of the file for display of facet names.
=> Connects to #1299 limit full results to gdm and interpretations, update facets and eslint

src/clincoded/static/libs/parse-pubmed.js
The following line would fail when `pubdate` is `null`, as returned by `parseDate()` previously in the `pubmedDatePublished()` function of `parse-pubmed.js`, specifically when the `PubDate` field in the XML specifically would have no Year, Month, and Day data (example pubmed [19464396](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=PubMed&retmode=xml&id=19464396)), causing an infinite spinning wheel on data retrieval w/ no data showing up:
```javascript
pubdate = pubdate.length < parseDate(day, month, year).length ? parseDate(day, month, year) : pubdate;
```
This PR has fixed the ternary so that it checks for a truth `pubdate` value first before checking for its `length`.:
Testing:
1. Attempt to add pubmed ID 19464396 via any pubmed add modal and confirm that it works
=> Connects to #1312. Fix pubdate ternary

src/clincoded/static/components/case_control_curation.js
1. Create a new GDM and add a new CaseControl evidence.
2. On the CaseControl curation form page, fill out all the required fields.
3. Make sure to enter data in the **Additional Information about Control Cohort** textarea.
3. Save the curation form and then go to the CaseControl **edit page** and/or **view page**.
4. Expect to see the data entered for "Additional Information about Control Cohort" being displayed.
=> Connects to #1315. Bug in which the 'Additional Information about Control Cohort' data did not get saved.

src/clincoded/static/components/variant_central/helpers/clinvar_interpretations.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/tests/features/select_variant.feature, src/clincoded/tests/features/variant_curation_tabs.feature
Updated `select_variant.feature` and `variant_curation_tabs.feature` BDD test assertions since we have removed the RCV table entries on the Basic Info tab.
1. In VCI, use **17000** for selecting the ClinVar and then proceed to the evidence view.
2. On the Basic Info tab, expect to see NO RCV entries being displayed in the **ClinVar Interpretations** table.
3. Also expect to see a line of text displayed below the **Clinical significance**, such as "Likely benign(5);Likely pathogenic(2);Pathogenic(7);Uncertain significance(3)", in the **ClinVar Interpretations** table. This is an "explanation" (included in the ClinVar API response) to the **Clinical significance**.
=> Connects to #1329. RCV table removal on VCI Basic Info tab.

src/clincoded/schemas/provisional_variant.json, src/clincoded/static/components/curator.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation/summary.js, src/clincoded/static/libs/bootstrap/alert.js, src/clincoded/static/libs/bootstrap/popover.js, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/static/scss/clincoded/modules/_popover.scss
1. Start a new VCI interpretation and evaluate some of the criteria so that a calculated pathogenicity is generated.
2. Click the **View Summary** button at the upper right hand corner to load the VCI Evaluation Summary page.
3. On the summary page, expect to see a new "Evidence Summary" label and its text field.
4. Enter some text into the "Evidence Summary" text field and click the **Save** button. Expect to see the form to be successfully saved and a green alert appearing next the button upon successful form submission (and disappearing in 6 seconds).
5. Click on the blue **?** icon with the "Mark status..." label above the text field and expect to see a popover appearing with new **Help** description. Click on the **?** icon again and expect to see it disappearing. …
=> Connects to #1330. Adding evidence summary text box in VCI.

src/clincoded/static/components/variant_central/helpers/hgvs_notation.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/computational.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/components/variant_central/interpretation/segregation.js, src/clincoded/static/components/variant_central/interpretation/shared/complete_section.js, src/clincoded/static/components/variant_central/interpretation/shared/form.js, src/clincoded/tests/features/variant_curation_tabs.feature
**Steps to test #1106:**
1. Visit the variant curation interface and select a variant (e.g. 55847). Proceed to the VCI evidence view.
2. Click on the **Population** tab and in the **Subpopulation with Highest Minor Allele Frequency** section, expect to see a newly added note text "This reflects the highest MAF observed, as calculated by the interface, across all subpopulations in the versions of ExAC, 1000 Genomes, and ESP shown below."
**Steps to test #1347:**
1. While still in the VCI, expect to see the **Segregation/Case** tab has been renamed to **Case/Segregation**.
**Steps to test #1450:**
1. While still in the VCI, click the **Predictors** tab and in the **ClinGen Predictors** table under the **Missense** sub-tab, expect to see the **0.329** REVEL score for the **55847** ClinVar …
=> Connects to #1106. Connects to #1347. Connects to #1450.

src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/segregation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
**Steps to test #847:**
1. Use the following example ClinVar IDs to test the **ExAC** linkout in the VCI's Popultation tab:
Substitution variants (with both clinvar and cadd objects):
http://myvariant.info/v1/variant/chr15:g.67358465C%3ET (VariationID: 139214)
http://myvariant.info/v1/variant/chr7:g.107423741C%3ET (VariationID: 55962)
Substitution variant (with only cadd object):
http://myvariant.info/v1/variant/chr1:g.957828A%3EC (CA501146)
Non-substitution variants (type "Duplication"):
http://myvariant.info/v1/variant/chr7:g.117232396dupA (VariationID: 7185)
http://myvariant.info/v1/variant/chr7:g.117171091_117171093dupCTA (VariationID: 53905)
Non-substitution variants (type "Deletion"):
http://myvariant.info/v1/variant/chr7:g.117188858del (VariationID: 53237) …
=> Connects to #847. Connects to #874. Connects to #987.

src/clincoded/static/components/errors.js, src/clincoded/static/components/variant_central/helpers/hgvs_notation.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/scss/clincoded/modules/_modal_disease.scss
**Changes and fixes in this PR:**
1. Added spacing in the order list for MonDO disease term search in the disease modal.
2. Updated the instructional text in the Auth0-related error messages.
3. Changed the external linkout text to "View the coverage in the ExAC region" in the ExAC population table when there is no ExAC data available.
4. Fixed the "View the coverage in the ExAC region" external linkout for "Deletion" variation type.
=> Changes and fixes for R12 release candidate 1

src/clincoded/static/components/errors.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/scss/clincoded/modules/_modal_disease.scss
1. Fixed list items' display issue in the disease modal when we are in the Group, Family, Individual and Case-Control curation forms.
2. Updated the instructional text in the Auth0-related error messages.
**Steps to test #1461:**
1. Create a new Group/Family/Individual/Case-Control curation in GCI.
2. Click on the add disease button (e.g. **"Disease+"**) to invoke the disease modal.
3. Expect to see the MonDO disease term search list item being displayed as the following:
=> Connects to #1461. Changes and fixes for R12 release candidate 2.

cloud-config.yml
Fixes Postgres issue by changing the recovery file name out right regardless of what type of instance is built. This will allow production to be built.
=> update fix for postgres for prod

src/clincoded/static/components/case_control_curation.js, src/clincoded/static/components/gene_disease_summary/case_control.js, src/clincoded/static/components/gene_disease_summary/case_level.js, src/clincoded/static/components/gene_disease_summary/case_level_segregation.js, src/clincoded/static/components/gene_disease_summary/experimental.js, src/clincoded/static/components/gene_disease_summary/header.js, src/clincoded/static/components/gene_disease_summary/index.js, src/clincoded/static/components/provisional_classification/index.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
1. Firefox browser is required to test a CSS bug associated with the checkbox for marking classification "Provisional".
2. A timezone change (to East Coast time) is required to test the rendering bug associated with the Evidence Summary page.
**Steps to test 1501:**
1. Create a new GDM.
2. Add 2-3 PMIDs to the GDM.
3. For each PMID in the GDM, add various types of evidence and score each one of them. For testing purpose, please have at least 3 scored proband evidence (with or without segregation), 2 segregation evidence without probands but with LOD scores, 2 scored case-control evidence, and 3 scored experimental evidence.
4. Upon having the minimum set of evidence added and scored, click the "View Classification Matrix" button at the upper right hand corner and …
=> Connects to #1501. Connects to #1503. Evidence Summary fixes.

src/clincoded/static/components/provisional_classification/index.js, src/clincoded/static/components/provisional_curation.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation/population.js
**Steps to test #1532:**
1. From the VCI variant selection interface, choose the ClinVar **139214** ID and proceed to the evidence-only view.
2. Click on the **Population** tab and _expect_ to see the display of the PAGE data table being suppressed.
**Steps to test #1531:**
1. In a new or existing GDM, create a new Family evidence curation and fill out the _required_ fields.
2. Select "Yes" for the **Published LOD score?:** option.
3. Enter "1.75" in the **Published Calculated LOD score:** input field.
4. Select "Yes" for the **Include LOD score in final aggregate calculation?** option.
5. Save the form without entering any proband information.
6. Return to Curation Central and click on the **View Classification Matrix** button at the upper right hand corner.
7. On the subsequent page, …
=> Connects to #1532. Connects to #1531.

.gitattributes
@jimmyzhen 
Only adds a `.gitattributes` file so that GitHub's language detector will ignore the generated db dumps (currently it mis-identifies these large files as Roff files and therefore the language percentage on the repo is substantially incorrect).
_Note:_ I am not sure if the overall GitHub language percentage display will be updated when dev is eventually merged to master or if it will display immediately since dev is the default branch.
To test locally
- `gem install github-linguist`
- In the dev branch run
`linguist`
```
93.38%  Roff
4.64%   JavaScript
1.58%   Python
0.35%   CSS
0.04%   Gherkin
0.01%   HTML
0.00%   Shell
0.00%   Ruby
0.00%   Makefile 
```
- In this branch run
`linguist`
```
70.12%  JavaScript
23.79%  Python
5.23%   CSS
0.63%   Gherkin
0.14%   HTML
0.05%   Shell …
```
=> correct repo language representation on github

src/clincoded/static/components/case_control_curation.js, src/clincoded/static/components/create_gene_disease.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/disease/interpretation.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/provisional_curation.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_curation.js, src/clincoded/static/scss/clincoded/modules/_dashboard.scss
1. Sign in as a member of an affiliation.
2. Go to the Gene-Disease Record page (aka Curation Central).
3. Edit an evidence that is associated with your affiliation.
4. Return to the GDM Record page and expect to see the evidence showing the your name and the timestamp that you last edited the evidence.
5. Now go to VCI and edit an interpretation that is associated with your affiliation.
6. Mark the interpretation as provisional in the summary and then return to the evaluation view.
7. Expect to see the button color for the Disease Delete button in Interpretation being red.
8. After that, return to the Dashboard page and expect to see the interpretation history item NOT showing the "last edited by" text in the "Recent History" panel.
9. And now sign in without any …
=> Connects to #1573. R15rc2 bug.

src/clincoded/static/components/gene_disease_summary/case_control.js, src/clincoded/static/components/gene_disease_summary/case_level.js, src/clincoded/static/components/gene_disease_summary/case_level_segregation.js, src/clincoded/static/components/gene_disease_summary/experimental.js, src/clincoded/static/components/gene_disease_summary/index.js
**Steps to test #1518:**
1. Add a **PMID** with multiple authors to an existing GDM or a newly created GDM.
2. Add and score evidence that can be scored, such as _Proband_, _Case-Control_ and _Experimental_.
3. Click on the **Preview Evidence Summary** button at the upper-right to open the **Evidence Summary** in a new tab/window.
4. In the **Evidence Summary** view, expect to see the authors of the paper (PMID) in the **Reference** columns of difference evidence tables to be shown in the format **"[lastname] [firstname Initial], et al."**
**Steps to test #1540:**
1. Close the _Evidence Summary_ tab/window and return to the GDM with the evidence from the previous testing steps.
2. Edit the **Case-Control** evidence by removing the associated disease and add an _HPO ID_ and/or a _free text …
=> Connects to #1518. Connects to #1540. Connects to #1560. Connects to #1582. 

src/clincoded/static/components/dashboard.js
#Updates:
--updated dashboard.js with props.last_name to show full demo username eg, Clingen Test Curator when demo user logs in.
Testing:
--user should log in to demo with Demo Login and see "Clingen Test Curator" in Welcome text
--Clingen Test User should be displayed where ever demo user edited or created any records.
=> Connects to #1541. Change "ClinGen Curator" display name to "ClinGen Test Curator" in demo version 

src/clincoded/static/components/case_control_curation.js
Update:
-- Removed word "Allele" from case_control_curation.js
-- Corrected the B Power Section to "Control Frequency".
Testing:
-- Users should log in and when curating Case and Case Control Power sections you should only see "Case Frequency" and not "Case Allele Frequency.
-- Users should also see "Control Frequency" instead of Case Frequency under B power section.
=> Connects to #1578.  Remove word "allele" from case control

src/clincoded/static/components/experimental_curation.js
Update:
-- Corrected text in experimental_curation.js for Experimental Data/Expression sections A and B
Testing:
-- Users should see "Organ or tissue relevant to disease (Uberon ID):" instead of "Organ of tissue relevant to disease, in which gene expression is examined in patient (Uberon ID):" for expression A.
-- Users should see "Organ or tissue relevant to disease (free text):" instead of "Organ of tissue relevant to disease, in which gene expression is examined in patient (free text):" for expression A.
-- Users should see "Organ or tissue relevant to disease (Uberon ID):" instead of "Organ of tissue relevant to disease, in which gene expression is examined in patient (Uberon ID):" for expression B.
-- Users should see "Organ or tissue relevant to disease (free text):" instead of …
=> Connects to #1487. Text changes in experimental expression

src/clincoded/static/components/gene_disease_summary/case_control.js, src/clincoded/static/components/gene_disease_summary/case_level.js, src/clincoded/static/components/gene_disease_summary/case_level_segregation.js, src/clincoded/static/components/gene_disease_summary/index.js, src/clincoded/static/libs/get_hpo_term.js, src/clincoded/static/scss/clincoded/modules/_gene_disease_summary.scss
**Steps to test #1592:**
1. In a Gene-Disease Record, add 2 **Individual** evidence and score both of them. In each of the evidence, add HPO IDs **"HP:0002629, HP:0002627"** and **"HP:0002626"** respectively in the **Phenotype(s) (HPO ID(s)):** textfield.
2. In the same record, add 2 **Family** evidence and produce LOD score for both of them. In each of the evidence, add HPO IDs **"HP:0002625, HP:0002624"** and **"HP:3000043"** respectively in the **Phenotype(s) in Common (HPO ID(s)):** textfield.
3. In the same record, add 2 **Case-Control** evidence and score both of them. In each of the evidence, instead of associating with a disease, add HPO IDs **"HP:0025491, HP:3000059"** and **"HP:0001015"** respectively in the **Phenotype(s) in Common (HPO ID(s)):** textfield for CaseCohort.
4. …
=> Connects to #1592. Connects to #1519.

src/clincoded/static/components/variant_central/interpretation/population.js
1. In the VCI, select ClinVar ID **6762** and proceed to the Evidence View.
2. Click on the Population tab and scroll to the PAGE Study table.
3. Expect to see the **African American** population has a **C: 0.00012** allele frequency instead of **C: 0.12300**. 
4. And expect to see the **Cuban** population has a **C: 0.00024** allele frequency instead of **0.23640**.
=> Connects to #1624. Page Study data patch.

src/clincoded/static/components/case_control_curation.js, src/clincoded/static/components/curator.js, src/clincoded/static/components/experimental_curation.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/components/provisional_curation.js, src/clincoded/static/components/score/experimental_score.js, src/clincoded/static/components/score/individual_score.js
**Steps to test #1626:**
1. Login as part of an affiliation, and curate 3 proband evidence with 3 different variants in a GDM.
2. At the top of the gene-disease record page, click on the individual variant link buttons to curate each variant.
3. Upon curating the variants, click on each of the variant link buttons to go back into each of the curated variants. Expect to see each of the different variants retaining their own curation info.
4. Return to the Dashboard page and change to a different affiliation.
5. Go to the same GDM and curate the same 3 variants.
6. Expect to see each of the different variants retaining their own curation info, as well as showing the correct curations from the prior affiliation.
**Steps to test #1628:**
1. In a GDM, curate and score a proband evidence.
2. …
=> Connects to #1626. Connects to #1628. Connects to #1629.

cloud-config.yml
Updated cloud-config.yml to use 8g of memory if production data is used for instance creation, else it will use 2g for demo data.
=> 1641 elasticsearch oom error

buildout.cfg, ez_setup.py
I have added two other hosts in our buildout.cfg: pypi.org and files.pythonhosted.org.
Also, I have updated our ez_setup with the correct default version and default URL.
Thank you @forresttanaka and @jimmyzhen for finding these corrections.
To test these changes I ran the make clean for my local environment and then ran the buildout script `python3.4 bootstrap.py -v 2.9.5 --setuptools-version 15.2`.
- If the changes did not work I should see an error saying that the file for setuptools downloaded is not a .zip file.
- The changes did work and I saw the build out script run and complete successfully.
=> Updated buildout.cfg and ez_setup.py for setuptools Connects to #1653

src/clincoded/upgrade/provisionalClassification.py
1. Spin up an instance with a backup copy of the production data prior to 2018-04-18.
2. Run the `batchupgrade` script on the instance.
3. Expect to see no errors incurred by the script.
4. Reindex the ElasticSearch data.
5. Go to ^/provisional/ and check the JSON data of individual `provisionalClassification` objects.
6. Expect to see the `totalScore` property being replaced by the `classificationPoints.evidencePointsTotal` property.
=> Connects to #1658. Upgrade script bug.

src/clincoded/upgrade/interpretation.py, src/clincoded/upgrade/variant.py
1. Spin up an instance with a backup copy of the production data prior to 2018-05-22.
2. Run the `batchupgrade` script on the instance.
3. Expect to see no errors incurred by the script.
4. Reindex the ElasticSearch data.
5. Go to ^/interpretation/ and check the JSON data of individual `interpretation` objects.
6. Expect to see the `schema_version` property value being `6` instead of `5`.
7. Go to ^/variant/ and check the JSON data of individual `variant` objects.
8. Expect to see the `schema_version` property value being `4` instead of `3`.
=> Connects to #1689. Upgrade script changes.

src/clincoded/static/components/app.js
I have added the latest version of Auth0 to app.js for install.
I have also added the correct URLs to Auth0 for allowed origins and callbacks.
I tested this from a demo instance:
- Install the latest Auth0 version
- Verify that I could log in via google
- Verify I could log in without google
- Be sure the curators could log in with both Google and text box.
Completion of testing showed that both I and the curators could log in with both Google and text box successfully.
=> Connects to #1701. Updating Auth0 lock to version 11.7.2.

cloud-config.yml
This will add the apache error logs to the awslogs. It was left out and had been added manually during a release. Now it has been added to the cloud-config so it will be added as the release is built.
=> Connects to #1713. Adding config for apache-error logs to also be sent to AWS.

cloud-config.yml, src/clincoded/static/components/provisional_classification/approval.js, src/clincoded/static/components/provisional_classification/index.js, src/clincoded/static/components/provisional_classification/provisional.js, src/clincoded/static/components/provisional_curation.js
1. Production data is required for testing.
2. Conduct tests on classifications with 10 or more scored evidence.
1. Assign yourself to affiliation **Autism and Intellectual Disability EP**.
2. Go to `^/provisional-curation/?gdm=1d6fa43a-afc2-4b66-b892-51a944cd28a4&edit=yes`.
3. Save the classification and proceed with provisioning/approving subsequently.
4. Expect to see the **Submit Provisional** and **Submit Approval** buttons to be disabled after they were clicked.
5. And expect to see no duplicate snapshots were created upon successfully saving the **Provisional** and/or **Approval** snapshots.
6. Now create a new GDM with a **Unknown** _Mode of Inheritance_ or with a _freetext_ disease term.
7. Add/score a Proband evidence and save the …
=> Connects to #1789. Duplicate snapshots.

src/clincoded/static/components/admin/reports/index.js
1. Production data is required for testing this PR.
2. Have the Chrome DevTools console open while testing.
1. Sign in as admin and go to `^/admin`.
2. On the landing page, select the **Gene-Disease Record Stats for Expert Panels** option from the reports selection dropdown.
3. Click the **Submit** button and expect to the stats table to be rendered without any Javascript errors.
=> Connects to #1827. R23rc1 bugs.

.travis.yml
Apparently Travis is now defaulting to using Windows NT if no OS/platform is specified, and as a result the tests on Sauce Labs fail when platform is not specified.
This change just directs Travis to use Linux as the platform for Sauce Labs to run the browser on (and also removed one non-significant whitespace at the end of a line elsewhere in the file).
- Sauce Labs:
https://app.saucelabs.com/builds/e7fb05f1f71648b68964090dcaa7f868
- Travis:
https://travis-ci.org/ClinGen/clincoded/jobs/465228236
-----
- add `dist: trusty`
(precise is being discontinued, as seen on https://blog.travis-ci.com/2017-08-31-trusty-as-default-status)
- upgrade Sauce Connect version from 4.4.2 to 4.5.2
- test against Windows or Mac in Sauce Labs
=> add platform/OS to Travis tests otherwise Sauce Labs runs as Windows NT

src/clincoded/static/components/select_variant.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation.js, src/clincoded/static/components/variant_central/interpretation/population.js
Steps to test #1715 
1. New Variant Curation, Search and Select Variant for the following:
- (ClinVar VariationID: 18000) represents a SNV (single nucleotide variant)
- (ClinVar VariationID: 372075) represents a 4bp deletion (indel variant)
2. Confirm red info card on Search/Select Variant reads "This version of the interface returns evidence for SNVs (single nucleotide variants) and for some small duplications, insertions, and deletions." 
3. Confirm that gnomAD/ExAC data for both variants renders in Population tab, along with their respective "link-outs" in header ("See data in gnomAD/ExAC")
=> Connects to #1715, Return gnomAD/ExAC data for indel variants in the VCI (Population Tab)

src/clincoded/static/components/variant_central/interpretation/computational.js
Error message (seen in browser console) before update:
Uncaught TypeError: Cannot read property 'mammalian' of undefined
Steps to test #1864:
1. Open the developer tools (to see the console) of your chosen browser.
2. Add a variant (e.g. ClinVar ID 21134).
3. Visit the "Population" and "Variant Type" tabs to confirm that the above error message doesn't appear and that all of the panels eventually display a table of data or a "no data was found" message (instead of a permanent "loading" message).
=> Connects to 1864. Fix processing/display of data from MyVariant.info in VCI.

cloud-config.yml, src/clincoded/static/components/curator.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/individual_curation.js
Issue #1326, #1808 - Allow copying of "not" phenotype information from Groups to Families and Individuals.
In GCI, Curation Central => Genetic Evidence sidebar.
- Can copy NOT Phenotype from (Group > Family), (Group > Individual), (Family > Individual)
- Displays NOT Phenotype information (HP ID, Free Text) associated with Group/Family that will be copied
Connects to issue #1866 - 
Typo under the Family-Segregation section was fixed. "UNAFFECTED" sentence: "biallelic" previously read "bialleltic".
=> Connects to #1326. Connects to #1808. Connects to #1866. Copy NOT Phenotypes information from Groups to Families and Individuals.

.travis.yml
Several Travis builds have completed successfully, and the corresponding logs have looked ok,  running the latest version of Sauce Connect (4.5.3), so I think it's safe to merge this change.
=> Connects to #1932. Updated to Sauce Connect 4.5.3

src/clincoded/messaging/__init__.py, src/clincoded/static/components/provisional_classification/snapshots.js, src/clincoded/static/components/variant_central/clinvar_submission.js, src/clincoded/static/scss/clincoded/modules/_approval.scss, src/clincoded/static/scss/clincoded/modules/_modal_clinvar_submission.scss, src/clincoded/static/scss/style.scss
Steps to test #1967:
1. Choose to curate as one of ClinGen's approved VCEPs (e.g. Cardiomyopathy).
2. Via the VCI's approval process, save, provision and approve an interpretation.
3. In order to see the **ClinVar Submission Data** button, the approval process can't be "active" (displaying a panel to approve or publish). So, if the button isn't present, either publish the approved interpretation (the default next step after approving) or click the **Return to Interpretation** button (to exit the approval process) and then click the **View Summary** button (to return to the approval process).
4. Click the **ClinVar Submission Data** button, which should open a **ClinVar Submission Data** modal.
5. Click the **Generate** button in the modal. If the generation process is successful, a single …
=> Generate ClinVar Submission Data from Approved Interpretations

src/clincoded/static/components/affiliation/affiliations.json, src/clincoded/static/components/variant_central/clinvar_submission.js
Steps to test #1982:
1. Choose to curate as an affiliation.
2. Via the VCI's approval process, save, provision and approve an interpretation.
3. In order to see the **ClinVar Submission Data** button, the approval process can't be "active" (displaying a panel to approve or publish). So, if the button isn't present, click the **Return to Interpretation** button (to exit the approval process) and then click the **View Summary** button (to return to the approval process).
4. Click the **ClinVar Submission Data** button, which should open a **ClinVar Submission Data** modal.
5. Click the **Generate** button in the modal. If the generation process is successful, a single row of data, pulled from the interpretation, should be displayed and the **Copy (to clipboard)** button should be enabled. …
=> Allow All Affiliations to Generate ClinVar Submission Data + Affiliation Updates

src/clincoded/static/components/add_external_resource.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/variant_central/index.js, src/clincoded/static/components/variant_central/interpretation/population.js, src/clincoded/static/libs/parse-resources.js
Steps to test #2034:
1. Start a new variant curation (based on ClinVar ID).
2. Upon retrieving the variant from ClinVar, check that the **HGVS terms** list includes items identified as GRCh37 and/or GRCh38 (in parenthesis after the term). If such items aren't included, it likely means the data isn't present in ClinVar's E-utilities XML (and a new variant should be selected).
3. Upon saving the variant and being taken to the evidence view, confirm that the "variant is not associated with a GRCh37 genomic representation" warning does not appear.
4. Start the interpretation and confirm there are no problems with existing functionality (adding a disease, inheritance, criteria evaluations, PMID evidence, etc.). If curating as an affiliation, use the approval process to approve the …
=> Updated Parsing of ClinVar E-utilities XML (to support VCV format)

src/clincoded/static/components/provisional_classification/approval.js, src/clincoded/static/scss/clincoded/modules/_approval.scss
Help text is found in GCI, once the user reaches Approval Preview
=> adds help text to approval preview in GCI

src/clincoded/static/components/add_external_resource.js
Steps to test #2115:
1. Start the application and run the browser (bdd) test locally (to confirm no failures).
To see how the update impacts the display of the "add variant" modal, compare the results of retrieving variants by ClinVar ID, such as 224885, both locally and on the demo site.
=> Update to Display Logic of Add Variant Modal (to fix automated tests)

src/clincoded/schemas/provisionalClassification.json, src/clincoded/schemas/provisional_variant.json, src/clincoded/schemas/resourceHistory.json, src/clincoded/static/components/provisional_classification/approval.js, src/clincoded/static/components/provisional_classification/provisional.js, src/clincoded/upgrade/provisionalClassification.py, src/clincoded/upgrade/provisional_variant.py, src/clincoded/upgrade/resourceHistory.py
Steps to test #2132:
1. Start a new curation (gene or variant).
2. Run through the approval process (save, provision and approve) multiple times.
3. Check the resulting provisional and latest snapshot objects to confirm there's, at most, one snapshot array reference (`associatedClassificationSnapshots` for gene curation, `associatedInterpretationSnapshots` for variant curation).
=> Update to Prevent (and Remove Existing) Provisional/Snapshot Data Nesting

src/clincoded/static/components/case_control_curation.js, src/clincoded/static/components/family_curation.js, src/clincoded/static/components/gene_disease_summary/case_control.js, src/clincoded/static/components/gene_disease_summary/case_level.js, src/clincoded/static/components/gene_disease_summary/case_level_segregation.js, src/clincoded/static/components/gene_disease_summary/index.js, src/clincoded/static/components/globals.js, src/clincoded/static/components/group_curation.js, src/clincoded/static/components/hpo_term_modal.js, src/clincoded/static/components/individual_curation.js, src/clincoded/static/scss/clincoded/modules/_curator.scss, src/clincoded/static/scss/clincoded/modules/_gene_disease_summary.scss
Issue #1585 
- Curate a new Gene-Disease record, and save an article by adding PMID
- The Modal lives in the Group, Family, and Individual sections of the Case-Level Genetic Evidence for the article (right hand side of curation-central)
- Modal is rendered by clicking "HPO Terms +" button
**The Modal should:**
- Validate that the user is entering an HPO (or comma separated list of IDs) with the correct format, if not, a red validation message should prompt the user
- Allow users to enter a full list of comma separated HPO IDs, as well as append to the list in the modal one-by-one by clicking "Add"
- Support the ability to delete fetched HPO terms by clicking the red trash icons 
- Save the list of HPO terms to the state of the parent (i.e Group, Family, Individual), if …
=> Issue #1585 Display human-readable HPO terms in gene curations

src/clincoded/static/components/affiliation/affiliations.json
Updates for #2168:
For affiliation 10060, the name should now appear as **Syndromic Disorders** (including existing curation data).
=> Affiliation Name Change (#2168)

src/clincoded/static/components/gene_disease_summary/case_control.js, src/clincoded/static/components/gene_disease_summary/case_level.js, src/clincoded/static/components/gene_disease_summary/case_level_segregation.js, src/clincoded/static/components/gene_disease_summary/index.js
#1585 Due to HPO Term Modal feature, fetch functionality for HPO Terms was removed from the Evidence Summary component. It is now being reintroduced so users will be able to see the terms for their old IDs, and can slowly transition to using the modal as they edit evidence.
Right now, Evidence Summaries are only returning the "bare" IDs, whereas before terms were being displayed. I have reverted the code in the Evidence Summary to again fetch the term names for HPOs. 
If a user has fetched the term name using the new modal, the request is made again inside the Summary for the sake of a consistent format for these terms.
PDF showing the bare ID issue:
[SCP2_LDMNS_Evidence Summary_20200323.pdf](https://github.com/ClinGen/clincoded/files/4377602/SCP2_LDMNS_Evidence.Summary_20200323.pdf) …
=> #1585 - HPO Terms in Evidence Summary

src/clincoded/static/components/add_curator.js, src/clincoded/static/components/add_disease.js, src/clincoded/static/scss/clincoded/modules/_form.scss, src/clincoded/tests/features/select_variant.feature
This ticket does not directly address #2136, but fixes an issue with the tool that's needed to make the data change. Also includes a small styling fix and a temporary automation test text change
**Steps to test /add-disease**
1. Login
2. Go to /add-disease
3. Find a disease to add from https://www.ebi.ac.uk/ols/index (I used MONDO:0011581)
4. Fill out the fields on the add disease page and click save.
5. Expect action to be successful. Ensure feedback text does not overlap with "Save" button.
=> #2136: Add Disease Page Fix

src/clincoded/static/components/create_gene_disease.js, src/clincoded/static/libs/parse-hgnc.js
Steps to test #1988:
1. Start a new gene curation.
2. Confirm that a gene-disease record can be created when:
- providing a symbol for a gene not present in the test dataset, such as AAAS, ZMYM6, NKX2-5 or C12ORF65
- providing a symbol for a gene in the test dataset, such as DICER1, FGFR3 or SMAD3 (for these examples, the process should update the locally-stored gene)
3. Confirm that a gene-disease record isn't created when providing data that matches an existing one, such as FANCM (gene), MONDO:0019391 (disease) and Other (mode of inheritance).
=> Retrieve Gene Information from HGNC (#1988)

src/clincoded/static/components/variant_central/interpretation/basic_info.js, src/clincoded/static/scss/clincoded/modules/_curator.scss
- Fix text overflow for super long nucleotide change, for refseq, ensembl and primary transcript table in basic info tab. Resolve overflow [reported by Matt in 1868](https://github.com/ClinGen/clincoded/issues/2126#issuecomment-622597404). You can test by adding variant Clinvar ID `90973` to verify the super long variant title displayed in VCI basic info tab.
- Let add variant modal elapses / "dot dot dot truncating" remain.
[Test instance](https://2126-sc-mane-visual-cue-rev07.demo.clinicalgenome.org).
Previous PR: #2195
=> Patch 2126: Fix Text Overflow

src/clincoded/static/components/provisional_curation.js
Steps to test #2187:
1. Start a new gene curation.
2. Add more than 11 points of scored evidence, some of which must be genetic (e.g. a proband individual).
3. Go to the classification matrix page and confirm that using the "Replication Over Time (Yes/No)" checkbox changes the "Calculated Classification" between "STRONG" and "DEFINITIVE".
=> Fixed Behavior of "Replication Over Time" Checkbox (#2187)
