ClinGen/clincoded

.travis.yml

--Travis CI set up for clincoded at https://travis-ci.org/
--Sauce Labs account set up for clincoded at https://saucelabs.com/
--.travis.yaml on repo changed to use encrypted variables for clincoded's Sauce Labs account per the Travis CI docs (http://docs.travis-ci.com/user/encryption-keys/ and http://docs.travis-ci.com/user/sauce-connect/)
--See ticket #35 for screenshots and more info

Connects to #35 kd Travis CI and Sauce Labs setup

---

src/clincoded/tests/data/inserts/user.json

Add @mrmin123 to dev db user inserts (user.json)

Connects to #67. Add new developer to user.json

---

src/clincoded/schemas/annotation.json
src/clincoded/schemas/gdm.json
src/clincoded/tests/data/inserts/annotation.json
src/clincoded/tests/data/inserts/gdm.json
src/clincoded/types/__init__.py

1) delete gdmId in gdm.json and annotationId in annotation.json.
2) use uuid as identifier

Connect to #70 use uuid to replace object id in gdm and annotation

---

src/clincoded/static/components/errors.js
src/clincoded/static/components/footer.js
src/clincoded/static/components/globals.js
src/clincoded/static/components/home.js

* Changed ENCODE references in files listed in #85
* Changed support email to clingen-helpdesk@lists.stanford.edu as referenced in #85 
* Relates to #94

Connects to #85 change encode refs

---

src/clincoded/static/components/curation_central.js
src/clincoded/static/components/curator.js
src/clincoded/static/libs/parse-pubmed.js
src/clincoded/tests/data/inserts/article.json

Fixed references to firstAuthor to authors to allow PubMed lookups to look again.

Connects to #115 ft update to schema

---

src/clincoded/static/components/curation_central.js

Fixes/works around these issues:
* When following a link to the curation center (same window/tab), the PMID is not automatically selected
* After selecting a different article, navigating out of the curation center retained the curation center URL in the address bar
* After selecting a different article, navigating using the back/forward controls were finicky at best, broken at worst.
* The workaround for this proved to be changing the window.history.pushState to window.history.replaceState. This means that selecting different articles in curation central, despite having the URL change, does not result in extra items in the history, so hitting back and/or forward would take you out of curation central entirely, instead of selecting a different article as previously.

Connects to #118. Curation Center PMID URL bugs

---

src/clincoded/static/components/dashboard.js

Added key property as suggested by @forresttanaka ; warning no longer occurs.

Connects to #129. Fix react warning on Dashboard page

---

src/clincoded/static/components/app.js
src/clincoded/static/libs/bootstrap/navigation.js
src/clincoded/static/scss/clincoded/_base.scss
src/clincoded/static/scss/clincoded/modules/_navbar.scss

* Changed Dashboard menu item to house icon.
* Fixed Login menu on mobile devices
* Fixed user navigation spacing on mobile devices

Connects to #86 ft menubar

---

src/clincoded/static/components/create_gene_disease.js
src/clincoded/static/libs/bootstrap/form.js
src/clincoded/static/libs/bootstrap/modal.js
src/clincoded/tests/features/create_gene_disease.feature

* Fixed ```<select>``` form value processing to detect required fields more reliably.
* Added ```<Alert />``` component to modals.js for modals that appear programmatically instead of in response to a click, a la ```<Modal />```. Post 0.5, I should look at cleaning up the modals.js code so Alerts and Modals are more like each other.
* Changed blue confirmation buttons (**Curate** and **Submit**) to white instead of blue so that they don’t give the impression that there’s a key equivalent (*Enter*) for these. Still need code to prevent Enter key from submitting forms (https://github.com/ClinGen/clincoded/issues/144).
* Submitting a Create Gene-Disease form now brings up an alert if the specified G/D/M already exists in the DB. The alert gives the option of curating the existing GDM on the …

Connects to #93 ft gdm exists

---

src/clincoded/schemas/gdm.json
src/clincoded/static/components/curation_central.js
src/clincoded/static/components/curator.js
src/clincoded/types/__init__.py

Summary of changes.
1. Add a calculated property "status" in gdm. Its value is automatically assigned. Handling scripts in /types/init.py
2. Edit /static/components/curation_central.js for change 1. Need re-run buildout for this change.
Create a new gdm, add new PMID, and add new group are tested successfully.
DB dump files for testing data only and for full HGNC gene and Orphanet disease data are included.

Connect to #165 kl calculated status in gdm

---

src/clincoded/static/components/app.js
src/clincoded/static/scss/clincoded/_base.scss

Removed margin below noticebar; removed rounded corners on noticebar

Connects to #176. Noticebar CSS fix

---

src/clincoded/static/components/app.js

Connects to #168. Add hover text to Dashboard menu icon

---

src/clincoded/static/components/create_gene_disease.js

Previous updates by @forresttanaka addressed most of the items on this issue as shown:
No Mode of Inheritance selected:
GDM Collision message:
This PR updates the GDM collision message as discussed.

Connects to #126. Update GDM collision feedback msg

---

src/clincoded/static/components/dashboard.js

Small text change on dashboard from:
"Your curator status:"
to:
"Your status:"

Connects to #209 change curator status text

---

src/clincoded/loadxl.py
src/clincoded/schemas/experimental.json
src/clincoded/schemas/family.json
src/clincoded/schemas/gdm.json
src/clincoded/schemas/group.json
src/clincoded/schemas/individual.json
src/clincoded/search.py
src/clincoded/static/components/search.js
src/clincoded/tests/data/inserts/experimental.json
src/clincoded/tests/data/inserts/family.json
src/clincoded/tests/data/inserts/gdm.json
src/clincoded/tests/data/inserts/group.json
src/clincoded/tests/data/inserts/individual.json
src/clincoded/types/__init__.py

Summary of changes.
1. Embed method as sub-object in group, family and individual.
2. Embed assessments as sub-object in gdm/variantPathogenic, family/segregation and experimental.
3. Edit test data for schema changes above.
4. Edit search.py and /static/components/search.js. Need to re-run bin/buildout.

Connects to #206 kl embed method and assessment

---

src/clincoded/static/components/dashboard.js

I saw the use of the `userMatch` global in #225 and decided to update the Dashboard's user checking functionality to use that instead. Hopefully this will help keep things consistent down the line. No visible UI changes.

Connects to #214. Update dashboard to use userMatch global

---

docs/database-dumping.rst

Documentation explaining why and how to update the two test database dumps.

Connects to #227. Add test database dump docs

---

.travis.yml

Increase timeouts for tests to reduce the Sauce Connect failures and upgrade Sauce Connect

Connnects to #142 Kd increase browser test timeout

---

README.rst
pytest.ini

Requires [ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/home) to be installed for it to [work with splinter](http://splinter.readthedocs.org/en/0.1/setup-chrome.html) on your machine!
Install using brew:
brew install chromedriver
Local browser tests running in Chrome:

Connects to #222. Change test browser to Chrome

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/group_curation.js

1. Create a new group.
2. On the group submit page, look for the title with the **View** and **Edit** buttons. Click the **Edit** button.
3. Change any value on the Group edit page and click **Save**. You return to the group submit page.
4. Choose the **No** option and click the button for going back to the Record Curation page.
5. Look for the group you created and click its **Edit** link.
6. Change any value on the Group edit page and click **Save**. You return to the Record Curation page instead of the group submit page.
1. Create a new family.
2. On the family submit page, look for the title with the **View** and **Edit** buttons. Click the **Edit** button.
3. Change any value on the Family edit page and click **Save**. You return to the family submit page.
4. Choose the **No** option …

Connects to #242 ft edit submit

---

src/clincoded/static/components/family_curation.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

1. Create a group; minimal information is fine.
2. Create a family unassociated with a group; minimal information is fine.
3. View the family. It should display **Family: *family name***.
4. Go back to Record Curation and Click **Add new Family to this Group** and create a new family that’s associated with the group you made before.
5. View this family. It should display:
Family: *family name*
Group association: *group name*
1. Curate a family and go down to the variant panel. Enter **rs***10-digits*.
2. Click **Save**. You’ll get the error **Use dbSNP IDs (e.g. rs1748)**.
3. Change it to use nine digits instead.
4. Click **Save**. The family gets saved.

Connects to #7 ft alpha1 updates

---

src/clincoded/static/components/dashboard.js

Testing (confirm proper update in dashboard after each step):
1. Create GDM
2. Add PMID
3. Add Individual (no Family and Group association)
4. Add Family (no Group association)
5. Add Individual to Family created in step 4
6. Add Group
7. Add Family to Group created in step 6
8. Add Individual to Family created in step 7
9. Add Individual to Group created in Step 6

Connects to #276. Add Individuals support to Recent History in Dashboard

---

src/clincoded/static/components/family_curation.js
src/clincoded/static/components/group_curation.js
src/clincoded/static/components/group_submit.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/components/methods.js
src/clincoded/static/libs/bootstrap/form.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

1. From Record Curation, click **Family +**
2. Enter at least the name and Orphanet IDs.
3. Scroll down to the “Methods” section and verify one text area is labeled “Description of Method(s)” instead of “Description of Methods by which specific mutations genotyped”
3. Scroll down to the Variant panel and click **Add variant associated with proband**. Verify the light green warning message appears.
4. Enter something in either “ClinVar VariationID” or “Other description.”
5. Click **Add another variant associated with proband**.
6. Verify the light green warning banner repeats for the second variant.
7. Verify the “Copy Orphanet IDs from Family” button’s left edge lines up with the left edge of the input field above it.
8. Fill out the “Individual Name” and “Orphanet Disease(s) for …

Connects to #284 ft postalpha2

---

src/clincoded/static/components/curator.js

* Go to an existing GDM, like [this one](http://localhost:6543/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a).
* Change the OMIM ID, then refresh the page to be sure. Verify the Creator of the GDM does not change.
* Add a PMID to the GDM, then refresh the page to be sure. Verify the Creator of the GDM still does not change.

Connects to #297 Copy submitted_by on update

---

src/clincoded/tests/data/inserts/user.json

Connects to #352 additional users

---

src/clincoded/tests/data/inserts/user.json

Connects to #352 kd new user

---

src/clincoded/tests/data/inserts/user.json

Connects to #352 additional user

---

src/clincoded/schemas/gdm.json
src/clincoded/static/components/create_gene_disease.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js

Testing:
1. Go to create GDM page
2. Confirm that 'Sporadic' is no longer an option for Mode of Inheritance
Testing:
1. Go to Family and Individual Curation pages
2. Confirm that the Add Variant buttons read 'Individual', not 'proband'
Family page:
Individual page:
Testing:
1. Go to Family Curation page
2. Confirm there is no notice above 'Add Variant' button
3. Add a variant
4. Confirm that notice appears above 'Add another variant' button
5. Add 2nd variant and confirm that notice (and button) disappears
6. Go to Individual Curation page
7. Confirm there is notice above 'Add another variant' button
8. Add 2nd variant and confirm that notice (and button) disappears
Family page:
Individual page:
Testing:
1. Go to Family and Individual Curation pages
2. Confirm that you cannot add more …

Connects to #368. Connects to #369. Connects to #370. Connects to #374. Connects to #376. UI Changes.

---

src/clincoded/tests/data/inserts/annotation.json
src/clincoded/tests/data/inserts/gdm.json
src/clincoded/tests/data/inserts/provisionalClassification.json

To facilitate demo, remove some test data

Connects to #386 kd remove some test data

---

prod-nginx.yml

Added starter file for base configs for prod SSL certificate handling.

Connects to #431 kd prod ssl server

---

src/clincoded/schemas/family.json

Testing:
1. Create GDM
2. Add PMID
3. Confirm that you can create Family w/ Ethnicity set to 'Unknown':

Connects to #436. Family ethnicity schema update

---

src/clincoded/schemas/individual.json

Allows for Individuals to be created w/ Ethnicity of 'Unknown'

Individual ethnicity schema update

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/globals.js
src/clincoded/static/components/group_curation.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/components/variant_curation.js

Testing:
1. Add GDM, add PMID
2. Go into add/edit G/F/I/E form and confirm that the PMID:XXXXX linkout exists at the top:
Testing:
1. Add GDM, add PMID, add something with variant
2. Go to variant curation page and confirm that the link exists
Testing:
1. Add GDM, add PMID
2. Add G/F/I/E
3. Confirm that linkout-able items (HPO, CL, EF, PMID, ClinVar, etc...) have valid linkouts:
* Linkouts to 'linked' Families and Groups:

Connects to #312. Connects to #332. Connects to #422. Various linkouts

---

src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js

Testing:
2. Create Group
3. Create Family associated with Group and confirm that button works as expected
4. Create Individual associated with Group and confirm that button works as expected
5. Create Individual associated with Family and confirm that button works as expected
6. Confirm that the button does not exist when creating Family and Individual not associated with Family and/or Group.
Family under Group:
Individual under Group:
Individual under Family:

Connects to #308. Copy orphanet button

---

src/clincoded/static/components/individual_curation.js

Testing:
2. Add Family w/o Proband
3. Attempt to add an Indiv associated with Family and confirm proband message (below)
4. Edit Family to add Proband Indiv w/ Variants
5. Go to the Proband Indiv's Edit page and confirm variant message (below)
In proband message:
In variant message:

Connects to #319. Linkouts to Family from Individual

---

src/clincoded/static/components/dashboard.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

* Update style of items on Dashboard
* Make entire GDM block in GDM list clickable
No entries:
With entries:

Connects to #403. Connects to #451. Updated Dashboard style

---

src/clincoded/static/components/app.js
src/clincoded/static/scss/clincoded/_base.scss

Testing:
1. Set up your hosts file so that a production.clinicalgenome.org points to localhost
2. Access instance/local server via production.clinicalgenome.org(:6543) URL and confirm that the production site warning is seen as above.

Connects to #467. Production site warning

---

src/clincoded/schemas/family.json
src/clincoded/schemas/individual.json
src/clincoded/static/components/curator.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/components/provisional_curation.js
src/clincoded/types/__init__.py

Update schemas (individual and family). Remove property diagnosis from required list. Edit items of columns in individual schema to display all individuals.
Update js files (individual_curation.js, family_curation.js and curator.js) to match the schema change.
Last dev merged e3591ff
**Test Steps**
* Create a proband individual (ind001) and leave input box "Orphanet Disease for Individual" empty, click Save.
Expect to see:
* Enter an Orphanet id into the box and click Save. Expect to save a new proband individual.
* Create a non-proband individual (ind002), leave the input box empty and click Save. Expect to save a non-proband individual.
* Edit ind002, enter an Orphanet id and save. Expect to save successfully.
* Create a family (family010), leave input box "Orphanet Common Disease(s) in …

Connects to #445. Connects to #468. kl remove requirement orphadisease in inidividual and family

---

src/clincoded/static/components/add_curator.js
src/clincoded/tests/data/inserts/user.json

--update add-curator (new curator is "curator" in groups)
--update test data for curators ("curator" in groups)
--update db dumps

Connects to #496 update add-curator groups, test data for curators, db dumps

---

src/clincoded/static/components/curation_central.js

Testing:
1. Create GDM
2. Add PMID(s)
3. Access GDM w/o specifying a PMID in the URL, and confirm that the first PMID item in the left-hand list is automatically selected

Connects to #316. Default PMID selection for GDMs

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/provisional_curation.js

Changes:
1. Greyed out Generate New Summary button in provisional curation page.
2. Redefine indexes of nested for loops in provisional_curation.js
**Test of Button**
* Create a GDM
* Add a PMID
* Add a proband individual (ind001) with a variant (111) associated
* Assess the variant to Support, expect to see a "Generate Summary" button.
* Generate a summary by click the button, then expect to see a greyed out and inactive "Generate New Summary" button in provisional curation page.
* Click Save, expect to see a regular "Generate New Summary" button in curation page.
**Test of For Loop Indexes**
* Add a non-proband individual (ind002), associat a variant (999) to it and assess the variant to Support.
* Add an experimental (expAAA) select Rescue/Patient Cell, associate variant 888 to it and …

Connects to #502 kl greyout button

---

src/clincoded/schemas/group.json
src/clincoded/static/components/curator.js
src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/group_curation.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/components/methods.js
src/clincoded/static/libs/bootstrap/form.js
src/clincoded/static/scss/clincoded/modules/_curator.scss
src/clincoded/static/scss/clincoded/modules/_form.scss
src/clincoded/types/__init__.py

**Changes for Ticket #328 and Ticket #511**
- Edit titles at data entrance boxes of Orphanet Disease, HPO id and Phenotype free text in group and family pages.
- Add a description for HPO and free text in group, family, individual and experimental pages.
**Change for Ticket #512**
- Edit title of method field in group, family and individual pages.
**Changes for Ticket #482 and Ticket #504:**
- Remove property commonDiagnosis from required list in group schema.
- Add controls for error handling when creating or editing a group.
- Add controls allowing delete Orphanet, hpo and free text in group, family and individual.
- Add controls for displaying and copying group Orphanet and phenotype to family and individual.
- Add controls for displaying and copying family Orphanet and phenotype to …

Connects to #482, Connects to #328, Connects to #511, Connects to #512, Connects to #504

---

src/clincoded/tests/data/inserts/user.json

Connects to #534 Jz add user

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js

Chnages:
1. Edit curator.js, family_curation.js, individual_curation.js and experimnetal_curation.js to shown yellow background of explanation of Phenotype is in experimental only.
but not in family and individual.
2. Edit handleClick function in family.js. Now, error message "Required" will be cleared after copy family Orphanet to proband individual.
**Test Steps**
* Create a family, enter Orphanet id, associate a variant, name an proband individual, leave Orphanet Disease(s) for Individual field empty, click Save. Expect to see error message "Required" under the field.
* Click "Copy Orphanet IDs from Family", expect to see no error message as:

Connects to #511 (yellow background), Connects to #482 (clear "Required" message after copy family Orphanet to proband individual)

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js

Experimental page:
Family:
Individual:

Connects to #540. Update HPO messages

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/components/provisional_curation.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

Tickets #514, #544, #546, #542 and #471.
**Change related to #542**
Add a warning for not using real name in individual page.
**Change related to #546**
Use html entity "&#8804" to replace "&#10877".
**Change related to #544 and #514**
Add a text with hyperlink to Mutalyzer.com in family, individual and experimental pages.
**Test for #544 and #514**
* Create a GDM,
* Add a PMID,
* Add a family and click "Add variant associated with individual" button. Expect to see "(e.g. HGVS, RCV, refSNP (rs) ID). For help in verifying, generating or converting to HGVS nomenclature, please visit Mutalyzer". 
* Click "Mutalyzer", expect to direct to https://mutalyzer.nl/ at a new tab.
* Click Cancel.
* Add an individual, expect to see the same text and link.
* Add experimental (Expression Type B, …

Connects to #544, Connects to #514, Connects to #546, Connects to #542, Connects to #471, Mutalyzer link and text

---

src/clincoded/static/components/family_curation.js

**Changes**
1. Edit flow steps for variant and proband data entry.
2. Edit code handling for submission.
**Test**
* Create GDM and add PMID.
* Add a family, name it Family010, click "Add variant associated with individual" button. Expect to open Family - Variant panel without proband individual fields. 
* Click Save button, expect to save the family successfully. Go back to curation-central page.
* Edit Family010. Associate variant 123, expect to see proband individual fields displayed (Required).
* Don't enter data, click Save. Expect to see error messages under the fields.
* Enter name and Orphernet id, click Save. Expect to save successfully.
* Add a new family, name it Family020, associate variant 123, name proband individual Ind021 and Orphanet id, then click "Add another variant …

Connects #503 kl no ind in family

---

src/clincoded/schemas/variant.json
src/clincoded/tests/data/inserts/variant.json
src/clincoded/types/__init__.py

**Changes**
1. Added a new property "clinvarVariantTitle" and edit items in columns in schema variant.json
2. Added related key:value pair for each variant in test data file.
3. Created a new small dump file.
**Test**
* Start with small group test data loaded.
* Go to ../variants/3b3af7f0-2685-11e5-bc56-60f81dc5b05a/?format=json
* Expect to see a new item "clinvarVariantTitle" like below.

Connects to #559 schema change for adding variant title in blue bar

---

src/clincoded/static/components/assessment.js
src/clincoded/static/components/curation_central.js
src/clincoded/static/components/curator.js
src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/libs/bootstrap/form.js
src/clincoded/static/libs/parse-resources.js
src/clincoded/static/scss/clincoded/_base.scss
src/clincoded/static/scss/clincoded/modules/_curator.scss
src/clincoded/static/scss/clincoded/modules/_form.scss

* New ClinVar VariationID add panel
* VariationID add modal
Testing:
2. Create Individual to test Add ClinVar VariationID modal:
1. Click button to ensure modal pops up
2. Enter ClinVar VariationID into input box; ensure that the button below input is enabled
3. Click button below input field, ensure that the cog appears, and then ensure that the correct ClinVar preferred title appears, and that the button to save becomes enabled
4. Change the value in the input box, and ensure that the previously fetched ClinVar preferred title disappears, and the Save button is disabled
5. Fetch again, then save
6. Ensure that the Other Description box is disabled, you get the ClinVar ID and Preferred Title on the main form, the ClinVar ID is linked, and the Add button becomes …

Connects to #543. Modal for obtaining external resources (ClinVar preferred titles)

---

src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/variant_curation.js
src/clincoded/tests/data/inserts/annotation.json
src/clincoded/tests/data/inserts/experimental.json
src/clincoded/tests/data/inserts/gdm.json

Testing:
2. Create Experimental Data object (and assess it)
3. Assess on it with another user
4. Go to Edit page with original user (should encounter disabled form due to other user assessment)
5. Hit back button to Curation Central
6. Go to Add another Experimental Data object
7. Confirm that the form is properly editable
8. Create Family object w/ Segregation data (and assess it)
9. Assess on it with another user
10. Go to Edit page with original user (should encounter un-editable Segregation section)
11. Hit back button to Curation Central
12. Click the 'Add Family' button ONCE and confirm that you go to the Add Family page (originally, you would encounter a JS error and the link would not work on first click)

Connects to #589. Disabled curation form

---

package.json
src/clincoded/static/components/app.js
src/clincoded/static/components/edit.js
src/clincoded/static/components/fetched.js
src/clincoded/types/__init__.py
src/clincoded/types/user.py

Updates:
--Update brace npm package to current version
--Restore ability to edit json
--Remove brace/ace blockScrolling deprecation console warning
--Update deprecated cloneWithProps to React.cloneElement
--Update some additional display references (change from ENCODE to ClinGen Curation)
--Some additional python minor formatting changes recommended by flake8 linter
Testing (admins only):
--Amend an object via the edit-json route (edit+save+view in another context)
--Users list (admin-only) should show "ClinGen Curation Users"

Connects to #620 fix edit json

---

src/clincoded/loadxl.py
src/clincoded/schemas/evaluation.json
src/clincoded/schemas/interpretation.json
src/clincoded/schemas/population.json
src/clincoded/schemas/provisional_variant.json
src/clincoded/schemas/variant.json
src/clincoded/tests/data/inserts/evaluation.json
src/clincoded/tests/data/inserts/interpretation.json
src/clincoded/tests/data/inserts/population.json
src/clincoded/tests/data/inserts/provisional_variant.json
src/clincoded/tests/data/inserts/variant.json
src/clincoded/types/__init__.py

**Changes:**
1. Added new schema files "evaluation.json", "population.json" and "provisional_variant.json" in dir `src/clincoded/schemas/`
2. Added new classes and functions in file `src/clincoded/types/__init__.py` to handle relationships of new schema objects above to objects "interpretation", "variant" and "orphaPhenotype".
3. Added related test data files "evaluation.json", "population.json" and "provisional_variant.json" in dir `src/clincoded/tests/data/inserts/`
4. Added mixins property "standard_status" in schema file  `src/clincoded/schemas/variant.json`
5. Modified variant test data in file `src/clincoded/tests/data/inserts/variant.json` to match current ClinVar values.
**View test data:**
[http://localhost:6543/evaluations](http://localhost:6543/evaluations) …

Connects to #679 kl schema evaluation and population

---

src/clincoded/loadxl.py
src/clincoded/schemas/computational.json
src/clincoded/schemas/evaluation.json
src/clincoded/schemas/population.json
src/clincoded/tests/data/inserts/computational.json
src/clincoded/tests/data/inserts/evaluation.json
src/clincoded/tests/data/inserts/interpretation.json
src/clincoded/types/__init__.py

**Changes in Schema Files** in dir `src/clincoded/schemas/`
1. Added a new file `computational.json`
2. Added a linkTo property in file `evaluation.json` to embed computational data.
3. Correct typo in file `population.json`
**Changes in Test Data Files** in dir `src/clincoded/tests/data/inserts/`
1. Added new file `computational.json`
2. Edited files `evaluation.json` and `interpretation.json` for including computational data
**Other Changes**
1. Added class and functions  in file  `src/clincoded/types/__init__.py` to handle relationships of computational object to objects evaluation, interpretation, variant and orphaPhenotype.
2. Edited file `src/clincoded/loadxl.py` to load computational data.
3. Created new small and large dump files
**View Test Data** …

Connects #689 kl computational schema

---

src/clincoded/schemas/computational.json
src/clincoded/schemas/population.json
src/clincoded/tests/data/inserts/computational.json
src/clincoded/tests/data/inserts/population.json
src/clincoded/types/__init__.py

**Changes in Schema Files** in dir `src/clincoded/schemas/`
1. Changed type of property "populations" from array to object in file `population.json`
2. Change type of calculated property "maf_count" from string to number in file  `population.json`
3. Changed type of property "computationalData" from array to object in file `computational.json`
**Changes in Test Data Files** in dir `src/clincoded/tests/data/inserts/`
1. Edited data in file `population.json` to match schema change.
2. Edited data in file `computational.json` to match schema change.
**Other Changes**
1. Edited function maf_count in file `src/clincoded/types/__init__.py` to match schema change.
2. Created new dump files.
**View Test Data**
[http://localhost:6543/populations/](http://localhost:6543/populations/) to view …

Connects to #714 kl convert array to object in schema

---

src/clincoded/tests/data/inserts/user.json

Connects to #752 add user

---

src/clincoded/static/components/variant_central/interpretation/basic_info.js
src/clincoded/static/components/variant_central/interpretation/population.js

Demo instance:
http://736-mc-calc-maf-9712c1e-minchoi.instance.clinicalgenome.org/
Images:
When an interpretation is started, the CI fields come back (CI fields are not yet implemented - See #737):
Testing:
1. Create Variant with data from one or more sources (population tab) - 139214, 139215, 41231
2. Check to see that information displayed in MAF area is correct

Connects to #736. MAF Calculations

---

src/clincoded/static/components/variant_central/interpretation/functional.js

Connects to #924. Experimental tab section titles

---

src/clincoded/static/components/variant_central/interpretation/shared/form.js

Testing:
1. Get to VCI and begin interpretation
2. Confirm that the evaluation dropdown values are spelled out as below

Connects to #958. Write out evaluation pulldown values

---

src/clincoded/schemas/gdm.json
src/clincoded/schemas/interpretation.json
src/clincoded/static/components/create_gene_disease.js
src/clincoded/static/components/curator.js
src/clincoded/static/components/mapping/modes_of_inheritance.json
src/clincoded/static/components/variant_central/actions.js
src/clincoded/static/components/variant_central/interpretation.js
src/clincoded/static/components/variant_central/title.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

* Added 'Evidence View' header text to VCI when in Evidence view mode
* Added `modeInheritance` field to `interpretation` object
* Moved mode of inheritance list out of `create_gene_disease.js` to external json file `modes_of_inheritance.json`
* Added `Oligogenic inheritance (HP:0010983)` value to modes of inheritance list
* Re-wire `create_gene_disease.js` to use `modes_of_inheritance.json` to generate dropdown list
* Update schemas for `interpretation` and `gdm` objects to allow new Oligogenic value
* Added 'Inheritance (+)` button to VCI, which switches to `Inheritance (pencil)` when mode of inheritance has been associated w/ interpretation
* Modified `Associate Disease` button to `Disease (+)`/`Disease (pencil)` button
* Added associate mode of inheritance modal to VCI
* Made it so …

Connects to #990. Connects to #837. Add MOI button to VCI

---

src/clincoded/schemas/gdm.json
src/clincoded/schemas/interpretation.json
src/clincoded/static/components/mapping/modes_of_inheritance.json

Replaces 'Oligogenic inheritance (HP:0010983)' entry with 'Multifactorial inheritance (HP:0001426)':
Schema update script not required as the Oligogenic Inheritance entry was new itself.

MOI item patch

---

src/clincoded/tests/data/inserts/user.json

-adds new test users
-updates alternate curator name display

patch to add new user

---

src/clincoded/schemas/caseControl.json
src/clincoded/tests/data/inserts/caseControl.json

In this PR, a new data property "label" is added in schema case control in file `src/clincoded/schemas/caseControl.json` and relevant test data is edited in file `src/clincoded/tests/data/inserts/caseControl.json`. In addition, new dump files are generated.
**Test**
* Go to [http://localhost:6543/casecontrol/2fa791d5-f1e4-4ede-8397-1c48a2e834e2/](http://localhost:6543/casecontrol/2fa791d5-f1e4-4ede-8397-1c48a2e834e2/) and expect to see `"label": "Case Control ABC",` in the case control object.

Connects to #1089 kl add label to casecontrol

---

src/clincoded/static/components/home.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

1) Add the following entries in the `/etc/hosts` file:
```
127.0.0.1    curation.clinicalgenome.org
127.0.0.1    curation-test.clinicalgenome.org
127.0.0.1    production.clinicalgenome.org
```
2) Go to **curation-test.clinicalgenome.org:6543** and expect to see the dark blue message in the light blue panel.
3) Go to **curation.clinicalgenome.org:6543** and expect to see the dark blue message in the light blue panel. Also expect to see a different message with an external link to the **curation-test.clinicalgenome.org** site.

Connects to #1082. Landing page demo site message.

---

src/clincoded/static/components/provisional_curation.js

Testing:
1. Get to GCI
2. Generate Summary
3. Ensure that the 'Autosomal Dominant' and 'Autosomal Recessive' cells have been updated as following (first 2 cells of 4th column):

Connects to #1226. Text update to Summary Table

---

src/clincoded/static/components/score/experimental_score.js
src/clincoded/static/components/score/individual_score.js

1. Create a new GDM. 
2. Add a Proband Individual evidence and score it.
3. Upon completion, return to the Proband form page or go to its View/Edit page. Click on the "Save" button without making any changes to the previously saved score input or selected options.
4. Return to the Proband form page or go to its View/Edit page, and expect to see those previously saved score input or selected options still being shown in the score panel.
5. Add an Experimental evidence and score it.
6. Upon completion, return to the Experimental form page or go to its View/Edit page. Click on the "Save" button without making any changes to the previously saved score input or selected options.
7. Return to the Experimental form page or go to its View/Edit page, and expect to see those …

Connects to #1246. Fixed bug in saving score without making any changes.

---

src/clincoded/static/components/variant_central/helpers/parse_key_value.js
src/clincoded/static/components/variant_central/index.js
src/clincoded/static/components/variant_central/interpretation/population.js

Other non-SNV variants for testing:
Duplication: 7185, 53905
Deletion: 53237, 53205, 13346
Insertion: 54032
Indel: 53981
**Steps to test all:**
(#1304) Go to VCI using any of the ClinVar IDs above. Cycle through different tabs, particularly the **Population** tab. Expect to be able to see the respective content of various tabs and none of the tabs are stalled.
(#1302) Return to the **Population** tab in VCI and click on the "Search gnomAD" link in the **gnomAD** panel. Expect to be taken to the gnomAD homepage given any of the ClinVar IDs above.
(#1303) While still on the **Population** tab, expect to see the "...for this variant." string being appended to the description in the panel.

Connects to #1302. Connects to #1303. Connects to #1304.

---

src/clincoded/static/components/curation_central.js

Removed message on editing gdm papers

Connects to #1350. removed warning for GDM curator

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/variant_central/interpretation/computational.js
src/clincoded/static/components/variant_central/interpretation/population.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

**Steps to test #1059:**
1. Start a new or an existing variant interpretation in the VCI.
2. Under the **Population** tab, expect to see the order of criteria in the evaluation form as shown below:
**Steps to test #1274:**
1. While still on the **Population** tab, expect to see the title of the **Highest Minor Allele Frequency** section now being **Subpopulation with Highest Minor Allele Frequency**.
2. Also expect to see the **Subpopulation with Highest Minor Allele Frequency** section is now directly above the **ExAC** table as shown below:
**Steps to test #1292:**
1. While still in the active interpretation mode in VCI, click on the **Predictors** tab.
2. On the **Missense** sub-tab, expect to see the order of criteria in the evaluation form as shown below:
**Steps to test #1358:**
1. …

Connects to #1059. Connects to #1274. Connects to #1281. Connects to #1292. Connects to #1317. Connects to #1358.

---

src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js

I modified bundle.js to exclude the curate variant link.

Connects to #1348. Removed curation link of variants 

---

cloud-config.yml

I have created a workaround for the cloud config to allow Postgres to complete its installation and allow the cloud-config to complete its installation and configuration of the instance
Steps to test are:
1.) Deploy instance using PR branch.
2.) I expect to see the instance start successfully.

Connects to #1431. AWS instance issue.

---

cloud-config.yml
src/clincoded/static/components/experimental_curation.js
src/clincoded/static/components/score/experimental_score.js

---
1. Start a new Experimental curation in GCI.
2. Select the **Biochemical Function** option for _Experiment type_.
3. Select the **A. Gene(s) with same function implicated in same disease** option for _Please select which one (A or B) you would like to curate_.
4. Expect to see the _Select Status_ selection dropdown being **disabled** in the **Exprimental Data Score** panel at the bottom.
5. Select the checkbox for _Has this gene(s) been implicated in the above disease?_.
6. Expect to see the _Select Status_ selection dropdown being **enabled** in the **Exprimental Data Score** panel at the bottom.
---
7. Now select the **B. Gene function consistent with phenotype(s)** option for _Please select which one (A or B) you would like to curate_ .
8. Expect to see the …

Connects to #1320. Experimental scoring bug.

---

.eslintrc.json
cloud-config.yml
src/clincoded/static/components/disease/individual.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/components/score/individual_score.js
src/clincoded/static/components/variant_central/interpretation/computational.js

**Steps to test #1301:**
1. Create a new **Group** curation in the GCI.
2. Fill out the **required** fields. **Associate** a disease with this Group evidence and add `HP:0010704, HP:0030300` to the **Phenotype(s) in Common (HPO ID(s))** text field.
3. Click the **Save** button and click on the **Add New Family for this Group** button to proceed to the **Family** evidence curation.
4. In the **Family** curation, click the **Copy all Phenotype(s) from Associated Group** button and expect to see the `HP:0010704, HP:0030300` string being added to the Family's **Phenotype(s) in Common (HPO ID(s))** text field.
5. Without adding a Proband to the Family, click the **Save** button. Expect to be able to save the curation successfully without being prompted for adding a Proband and its associated …

Connects to #1301. Connects to #1375. Connects to #1378. Connects to #1391.

---

src/clincoded/static/components/errors.js
src/clincoded/static/components/home.js
src/clincoded/static/scss/clincoded/modules/_curator.scss
src/clincoded/tests/features/create_gene_disease.feature
src/clincoded/tests/features/curation_central.feature
src/clincoded/tests/features/select_variant.feature
src/clincoded/tests/features/variant_curation_tabs.feature

**Steps to test #1440:**
1. Register a new account with Auth0 and follow up with the Auth0-sent account verification email. Without having been already added to the ClinGen user database, try to login and expect to see the **Registration not yet complete** message and new instructions.
2. Register a new account with Auth0 but do NOT follow up with the Auth0-sent account verification email. Without having been already added to the ClinGen user database, try to login and expect to see the **Auth0 account not yet verified** message and new instructions.
3. Log into the interfaces with verified Auth0 account and as a valid user in ClinGen's user database. After successfully logged in, delete the session cookie from the browser's Developer Tools. Refresh the page and expect to see the **Your …

Connects to #1440. Connects to #1442.

---

Gruntfile.js
src/clincoded/static/components/disease/modal.js
src/clincoded/static/components/provisional_curation.js
src/clincoded/static/components/score/constants/score_maps.js
src/clincoded/static/components/variant_central/interpretation/basic_info.js
src/clincoded/static/scss/clincoded/modules/_modal_disease.scss
src/clincoded/tests/data/inserts/user.json

**Steps to test #1339:**
1. Create 3 Proband Individual evidence in GCI and add at least one variant to each one of them.
2. Select the **Score** option from the **Select Status** in the **Score Proband** panel.
3. From the **Select a score different from default score** selection dropdown, expect to see the newly added **0.1** and **0.25** options.
4. Select **0.1, 0.1 and 0.25** respectively for each of the curation from the **Select a score different from default score** selection dropdown
5. Save each of the curation and click the **Generate Summary** button at the upper right hand corner.
6. In the Summary matrix, expect to see the scores with only 2 decimal digits.
(in contrast to the following)
**Steps to test #1390:**
1. Go to ^/create-gene-disease/ in GCI and click on the add …

Connects to #1339. Connects to #1390. Connects to #1434. Connects to #1454.

---

.travis.yml

I have corrected a few issues regarding TravisCI and their upgrades. This also contains the fixes that were implemented by Jimmy.
BOTO_CONFIG is now fixed
I have also specified the OS version that will be used to build which is the "precise" OS.
I tested this within TravisCI and with the corrections, there have been no build failures since the corrections.

Connects to #1470. Travis CI config update.

---

src/clincoded/static/components/disease/family.js
src/clincoded/static/components/disease/family_proband.js
src/clincoded/static/components/disease/gdm.js
src/clincoded/static/components/disease/group.js
src/clincoded/static/components/disease/individual.js
src/clincoded/static/components/disease/modal.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/scss/clincoded/modules/_curator.scss

1. In a new or existing GDM, create a new Family evidence curation.
2. Underneath the **Include LOD score in final aggregate calculation?** selection, expect to see a yellow alert box as shown below:

Connects to #1533. Segregation LOD Score note.

---

.travis.yml

1. Pull in this change in a local branch.
2. Push the local branch to the repo.
3. Expect to see the Travis CI build to pass.

Connects to #1555. Pre-install 'setuptools' with pip for Travis CI builds.

---

src/clincoded/static/components/curator.js
src/clincoded/static/components/dashboard.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/gene_disease_summary/index.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/scss/clincoded/modules/_gene_disease_summary.scss

1. Sign in as a member of an affiliation and expect to see the data loading much quicker in the variant interpretation and gene-disease record panels.
2. Also on the Dashboard page, expect to see a note in a blue box below the panels.
3. Create a new Family evidence and include a Proband in the evidence as a member of the affiliation. Save them, and in the Curation Palette, expect to see the "Edit" link for the Proband evidence as well as for the Family evidence.
4. Click on the "Review Evidence Summary" button to go to the evidence summary page, expect to be able to click on the PMID external links while the watermarks are present.

Connects to #1570. R15rc1 bugs.

---

src/clincoded/static/components/add_external_resource.js
src/clincoded/static/components/case_control_curation.js
src/clincoded/static/components/family_curation.js
src/clincoded/static/components/gene_disease_summary/case_control.js
src/clincoded/static/components/gene_disease_summary/case_level.js
src/clincoded/static/components/gene_disease_summary/case_level_segregation.js
src/clincoded/static/components/gene_disease_summary/index.js
src/clincoded/static/components/group_curation.js
src/clincoded/static/components/individual_curation.js
src/clincoded/static/libs/get_hpo_term.js

**Steps to test #1684:**
1. Go to the VCI and enter the **CA201843129** or **CA658795209** CA IDs as the selected variant.
2. Upon retrieving the variant data from **Allele Registry**, click the **Save** button the modal.
3. Expected to be able to successfully saving the variant to proceeding to the VCI Evidence view.
4. Other CA IDs can be used for testing -- **CA386972821, CA16020856, CA1944615, CA406293304, CA381513655, CA381513967, CA658795218, CA410676362, CA410677511, CA410677524, CA638504295, CA658795219, CA588838, CA412010809.**
**Steps to test #1687:**
1. In a GDM, curate/score 2 **Proband** evidence. For each of the **Proband** evidence, add the following lists of HPO IDs respectively: **List-1 -- HP:0001511, HP:0000126, HP:0030148, HP:0005164, HP:0001642, HP:0011994, …

Connects to #1684. Connects to #1687. Connects to #1688. Connects to #1690. Connects to #1691.

---

src/clincoded/static/components/affiliation/affiliations.json

Steps to test #1720:
1. Log in and associate yourself with the new affiliations (10028, 10029).
2. Log out and log back in to bring up the affiliation selection modal.
3. Select a new affiliation ("Hemostatis/Thrombosis EP" or "Broad Institute Rare Disease Group") and confirm that its name appears where expected (header, dashboard, approval process, etc.).

Connects to #1720. Add new affiliations.

---

README.rst
package.json

Features:
* Updated README.rst for current development environment
* Minor restructuring of document to make child nodes more
apparent/explicit
Fixes:
* Fixed RST compiler warnings
* Removed call to `postinstall.sh` due to missing `node_patches` folder

Connects to #1844. Update README for dev setup.

---

cloud-config.yml

To test #1911, run through all features/functionality of both interfaces (GCI and VCI) to confirm everything behaves as expected.

Connects to #1911. Updated Java install.

---

src/clincoded/static/scss/clincoded/modules/_gene_disease_summary.scss

#1983: Fixes PDF issue with word breaks in last column

Connects to #1983: Evidence Summary column issue

---

src/clincoded/tests/features/select_variant.feature
src/clincoded/tests/features/variant_curation_tabs.feature

Step to test #2016:
1) Trigger a Travis CI build (e.g. push a branch or create/update a pull request).

Updated Test Scenarios
